// Block definitions, procedural texture atlas, oriented logs, and item icons.
// THREE is a global provided by the engine bridge in index.html.

// Block IDs. 0 is always AIR.
const BLOCK = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  SAND: 4,
  WOOD: 5,        // vertical log (Y axis)
  LEAVES: 6,
  PLANK: 7,
  WATER: 8,
  BEDROCK: 9,
  GLASS: 10,
  BRICK: 11,
  COBBLE: 12,
  SNOW: 13,
  GRAVEL: 14,
  COAL_ORE: 15,
  IRON_ORE: 16,
  GOLD_ORE: 17,
  DIAMOND_ORE: 18,
  OBSIDIAN: 19,
  NETHERRACK: 20,
  GLOWSTONE: 21,
  LAVA: 22,
  PORTAL: 23,
  STONE_BRICK: 24,
  MOSSY_COBBLE: 25,
  WOOD_X: 26,     // log lying along X
  WOOD_Z: 27,     // log lying along Z
  CRAFTING_TABLE: 28,
  FURNACE: 29,
  TORCH: 30,
  FARMLAND: 31,
  WHEAT0: 32,    // seedling
  WHEAT1: 33,    // growing
  WHEAT2: 34,    // mature
  CHEST: 35,
  SAPLING: 36,
  TALL_GRASS: 37,
  FARMLAND_WET: 38,
  BED: 39,
  WOOL: 40,
  WOOL_RED: 41, WOOL_ORANGE: 42, WOOL_YELLOW: 43, WOOL_LIME: 44, WOOL_GREEN: 45,
  WOOL_CYAN: 46, WOOL_BLUE: 47, WOOL_PURPLE: 48, WOOL_PINK: 49, WOOL_BLACK: 50,
  AETHER_PORTAL: 51,
  AETHER_GRASS: 52,
  SANDSTONE: 53,
  // redstone
  REDSTONE_DUST: 54, REDSTONE_BLOCK: 55,
  REDSTONE_TORCH: 56, REDSTONE_TORCH_OFF: 57,
  LEVER: 58, LEVER_ON: 59,
  BUTTON: 60, BUTTON_ON: 61,
  REDSTONE_LAMP: 62, REDSTONE_LAMP_ON: 63,
  REPEATER: 64, REPEATER_ON: 65,
  PISTON: 66, PISTON_STICKY: 67, PISTON_HEAD: 68,
  COMPARATOR: 69, COMPARATOR_ON: 70,
};

// Each tile is generated by a painter function onto a 16x16 canvas.
const TILE = {};
let tileOrder = [];
function paint(name, fn) { TILE[name] = fn; tileOrder.push(name); }

// Helper: base fill + speckle noise for a natural look.
function speckle(ctx, base, spots, seed = 1) {
  ctx.fillStyle = base;
  ctx.fillRect(0, 0, 16, 16);
  let r = seed * 9301 + 49297;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  for (const [color, amount] of spots) {
    ctx.fillStyle = color;
    for (let i = 0; i < amount; i++) ctx.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  }
}
// Helper: scatter small blobs (for ores).
function blobs(ctx, color, count, seed) {
  let r = seed * 2654435761;
  const rnd = () => { r = (r * 1103515245 + 12345) & 0x7fffffff; return (r % 1000) / 1000; };
  ctx.fillStyle = color;
  for (let i = 0; i < count; i++) {
    const x = (rnd() * 13) | 0, y = (rnd() * 13) | 0;
    ctx.fillRect(x, y, 2, 2);
    if (rnd() > 0.5) ctx.fillRect(x + 1, y + 1, 1, 1);
  }
}

paint('grass_top', (c) => speckle(c, '#5fa83d', [['#6fbf48', 60], ['#4e8f33', 50], ['#75c850', 30]], 3));
paint('grass_side', (c) => {
  speckle(c, '#7a5a3a', [['#6b4d30', 50], ['#8a6a44', 40]], 5);
  c.fillStyle = '#5fa83d'; c.fillRect(0, 0, 16, 4);
  c.fillStyle = '#4e8f33';
  for (let x = 0; x < 16; x += 2) c.fillRect(x, 3 + ((x * 7) % 2), 1, 2);
});
paint('dirt', (c) => speckle(c, '#7a5a3a', [['#6b4d30', 60], ['#8a6a44', 45], ['#5e4329', 25]], 7));
paint('stone', (c) => speckle(c, '#888888', [['#777777', 70], ['#999999', 50], ['#6f6f6f', 25]], 11));
paint('cobble', (c) => {
  speckle(c, '#7c7c7c', [['#6a6a6a', 40], ['#909090', 30]], 13);
  c.strokeStyle = '#5c5c5c'; c.lineWidth = 1;
  c.strokeRect(0.5, 0.5, 7, 7); c.strokeRect(8.5, 4.5, 6, 6); c.strokeRect(2.5, 9.5, 6, 5);
});
paint('mossy', (c) => {
  speckle(c, '#6e7a5c', [['#5c6a4a', 40], ['#808c66', 30], ['#4a7a3a', 24]], 14);
  c.strokeStyle = '#4a5240'; c.lineWidth = 1;
  c.strokeRect(0.5, 0.5, 7, 7); c.strokeRect(8.5, 4.5, 6, 6);
});
paint('stonebrick', (c) => {
  speckle(c, '#8a8a8a', [['#7a7a7a', 40], ['#9a9a9a', 30]], 15);
  c.fillStyle = '#6a6a6a';
  c.fillRect(0, 7, 16, 1); c.fillRect(7, 0, 1, 8); c.fillRect(3, 8, 1, 8); c.fillRect(11, 8, 1, 8);
});
paint('sand', (c) => speckle(c, '#dcd29a', [['#d0c587', 60], ['#e8dfaf', 40]], 17));
paint('gravel', (c) => speckle(c, '#9a938c', [['#7f7872', 60], ['#b0a89f', 40], ['#6a6460', 24]], 18));
paint('wood_top', (c) => {
  speckle(c, '#b9925b', [['#a87f49', 30]], 19);
  c.strokeStyle = '#8a6a3f'; c.lineWidth = 1;
  for (let r = 6; r > 0; r -= 2) { c.beginPath(); c.arc(8, 8, r, 0, 7); c.stroke(); }
});
paint('wood_side', (c) => {
  speckle(c, '#6b4f2f', [['#5c4327', 40], ['#7c5d39', 40]], 23);
  c.fillStyle = '#4f3a22';
  for (let x = 2; x < 16; x += 5) c.fillRect(x, 0, 1, 16);
});
paint('leaves', (c) => speckle(c, '#3f8f33', [['#357a2b', 90], ['#4aa53c', 70], ['#2c6624', 40]], 29));
paint('plank', (c) => {
  speckle(c, '#b08a52', [['#9e7b46', 40]], 31);
  c.fillStyle = '#8a6a3f';
  for (let y = 0; y < 16; y += 4) c.fillRect(0, y, 16, 1);
  c.fillRect(7, 0, 1, 4); c.fillRect(11, 4, 1, 4); c.fillRect(4, 8, 1, 4); c.fillRect(9, 12, 1, 4);
});
paint('water', (c) => speckle(c, '#2b6fd6', [['#2461c4', 50], ['#3a80e8', 40]], 37));
paint('lava', (c) => {
  speckle(c, '#e2541a', [['#ff8a2a', 50], ['#c23a10', 40], ['#ffd24a', 20]], 38);
});
paint('bedrock', (c) => speckle(c, '#3a3a3a', [['#2a2a2a', 70], ['#4a4a4a', 50], ['#1f1f1f', 30]], 41));
paint('glass', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(180,220,235,0.25)'; c.fillRect(0, 0, 16, 16);
  c.strokeStyle = 'rgba(210,235,245,0.9)'; c.lineWidth = 1.5;
  c.strokeRect(1, 1, 14, 14);
  c.beginPath(); c.moveTo(3, 3); c.lineTo(7, 7); c.stroke();
});
paint('brick', (c) => {
  speckle(c, '#a44a3a', [['#933f30', 30]], 43);
  c.fillStyle = '#d8d2c4';
  for (let y = 0; y < 16; y += 4) c.fillRect(0, y, 16, 1);
  for (let y = 0; y < 16; y += 8) c.fillRect(8, y, 1, 4);
  for (let y = 4; y < 16; y += 8) { c.fillRect(4, y, 1, 4); c.fillRect(12, y, 1, 4); }
});
paint('snow', (c) => speckle(c, '#f2f7fb', [['#e4ecf3', 40], ['#ffffff', 40]], 47));
paint('coal_ore', (c) => { speckle(c, '#888888', [['#777777', 50], ['#999999', 30]], 11); blobs(c, '#1c1c1c', 5, 7); });
paint('iron_ore', (c) => { speckle(c, '#888888', [['#777777', 50], ['#999999', 30]], 11); blobs(c, '#c8a07a', 5, 9); });
paint('gold_ore', (c) => { speckle(c, '#888888', [['#777777', 50], ['#999999', 30]], 11); blobs(c, '#f5d23a', 5, 13); });
paint('diamond_ore', (c) => { speckle(c, '#888888', [['#777777', 50], ['#999999', 30]], 11); blobs(c, '#4fe0d8', 5, 21); });
paint('obsidian', (c) => {
  speckle(c, '#15101f', [['#0c0814', 60], ['#241b36', 30], ['#3a2a55', 12]], 53);
});
paint('netherrack', (c) => speckle(c, '#5e2a2a', [['#4a1f1f', 60], ['#722f2f', 40], ['#3a1818', 24]], 59));
paint('glowstone', (c) => speckle(c, '#d8a93a', [['#f0d469', 60], ['#b07e22', 40], ['#fff0a0', 24]], 61));
paint('craft_top', (c) => {
  speckle(c, '#9c7a47', [['#8a6a3c', 30]], 67);
  c.strokeStyle = '#5c4426'; c.lineWidth = 1;
  c.strokeRect(1.5, 1.5, 13, 13); c.beginPath();
  c.moveTo(8, 2); c.lineTo(8, 14); c.moveTo(2, 8); c.lineTo(14, 8); c.stroke();
});
paint('craft_side', (c) => {
  speckle(c, '#b08a52', [['#9e7b46', 40]], 31);
  c.fillStyle = '#6b4f2f';
  c.fillRect(0, 0, 16, 4);
  for (let y = 5; y < 16; y += 4) { c.fillStyle = '#8a6a3f'; c.fillRect(0, y, 16, 1); }
  c.fillStyle = '#6b4f2f'; c.fillRect(2, 6, 3, 3); c.fillRect(9, 10, 3, 3);
});
paint('farmland', (c) => {
  speckle(c, '#5a3d24', [['#4a3119', 50], ['#6b4d30', 30]], 79);
  c.fillStyle = '#3a2814';
  c.fillRect(2, 3, 12, 2); c.fillRect(2, 8, 12, 2); c.fillRect(2, 13, 12, 1);
});
paint('wheat0', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#5fa83d';
  for (let x = 3; x < 16; x += 4) c.fillRect(x, 11, 1, 4);
});
paint('wheat1', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#5a9a35';
  for (let x = 3; x < 16; x += 4) c.fillRect(x, 6, 2, 9);
});
paint('wheat2', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#c8a93a';
  for (let x = 3; x < 16; x += 4) { c.fillRect(x, 3, 2, 12); c.fillStyle = '#e8d36a'; c.fillRect(x, 3, 2, 3); c.fillStyle = '#c8a93a'; }
});
paint('sapling', (c) => {
  c.clearRect(0, 0, 16, 16);
  // little trunk
  c.fillStyle = '#7a5736'; c.fillRect(7, 10, 2, 5);
  c.fillStyle = '#5e421f'; c.fillRect(7, 13, 2, 2);
  // leafy canopy (rounded, layered greens)
  const leaf = (x, y, w, h, col) => { c.fillStyle = col; c.fillRect(x, y, w, h); };
  leaf(5, 4, 6, 6, '#3f8f33');
  leaf(4, 6, 8, 3, '#3f8f33');
  leaf(6, 2, 4, 3, '#4aa53c');
  leaf(5, 5, 2, 2, '#56b845'); leaf(9, 7, 2, 2, '#56b845');
  leaf(7, 3, 2, 2, '#56b845');
  leaf(4, 8, 2, 1, '#2f6e26'); leaf(10, 5, 2, 1, '#2f6e26');
  leaf(8, 8, 1, 1, '#2f6e26');
});
paint('tallgrass', (c) => {
  c.clearRect(0, 0, 16, 16);
  const blade = (x, col) => { c.fillStyle = col; c.fillRect(x, 6 + ((x * 5) % 3), 1, 9 - ((x * 5) % 3)); };
  for (let x = 2; x < 15; x += 2) blade(x, x % 4 === 0 ? '#4e9a36' : '#5fa83d');
  c.fillStyle = '#6fbf48'; c.fillRect(4, 5, 1, 3); c.fillRect(10, 6, 1, 3);
});
paint('farmland_wet', (c) => {
  speckle(c, '#3a2a16', [['#2e2010', 50], ['#46331b', 30]], 79);
  c.fillStyle = '#241a0c';
  c.fillRect(2, 3, 12, 2); c.fillRect(2, 8, 12, 2); c.fillRect(2, 13, 12, 1);
  c.fillStyle = '#2b3a6a'; c.fillRect(7, 3, 2, 2);   // damp sheen
});
paint('bed_top', (c) => {
  speckle(c, '#c0392b', [['#a83226', 30]], 91);
  c.fillStyle = '#ecf0f1'; c.fillRect(2, 2, 12, 5);   // pillow
  c.strokeStyle = '#8a2a20'; c.lineWidth = 1; c.strokeRect(1.5, 1.5, 13, 13);
});
paint('bed_side', (c) => {
  speckle(c, '#c0392b', [['#a83226', 30]], 93);
  c.fillStyle = '#6b4f2f'; c.fillRect(0, 12, 16, 4);  // wooden frame
  c.fillStyle = '#ecf0f1'; c.fillRect(1, 3, 4, 4);    // pillow edge
});
paint('wool', (c) => {
  speckle(c, '#ececec', [['#dcdcdc', 50], ['#fbfbfb', 40], ['#cfcfcf', 24]], 95);
});
// colored wool (Easter-egg wool world) — painted via WOOL_COLORS loop below
const WOOL_COLORS = [
  [BLOCK.WOOL_RED, 'wool_red', '#b5342a', 'Red Wool'],
  [BLOCK.WOOL_ORANGE, 'wool_orange', '#d27a1e', 'Orange Wool'],
  [BLOCK.WOOL_YELLOW, 'wool_yellow', '#e0c12c', 'Yellow Wool'],
  [BLOCK.WOOL_LIME, 'wool_lime', '#86d12c', 'Lime Wool'],
  [BLOCK.WOOL_GREEN, 'wool_green', '#3f8f33', 'Green Wool'],
  [BLOCK.WOOL_CYAN, 'wool_cyan', '#2aa9b5', 'Cyan Wool'],
  [BLOCK.WOOL_BLUE, 'wool_blue', '#2f5fc0', 'Blue Wool'],
  [BLOCK.WOOL_PURPLE, 'wool_purple', '#8a3fc0', 'Purple Wool'],
  [BLOCK.WOOL_PINK, 'wool_pink', '#e08ab0', 'Pink Wool'],
  [BLOCK.WOOL_BLACK, 'wool_black', '#2a2a2e', 'Black Wool'],
];
for (const [, tile, color] of WOOL_COLORS) {
  const shade = (hex, d) => {
    const n = parseInt(hex.slice(1), 16);
    const r = Math.max(0, Math.min(255, ((n >> 16) & 255) + d));
    const g = Math.max(0, Math.min(255, ((n >> 8) & 255) + d));
    const b = Math.max(0, Math.min(255, (n & 255) + d));
    return '#' + ((1 << 24) | (r << 16) | (g << 8) | b).toString(16).slice(1);
  };
  paint(tile, (c) => speckle(c, color, [[shade(color, 18), 45], [shade(color, -18), 40]], 7));
}
paint('aether_grass', (c) => {
  speckle(c, '#9fe0c0', [['#b6f0d6', 50], ['#7fc8a6', 40]], 71);
});
paint('sandstone', (c) => {
  speckle(c, '#dcd29a', [['#cabd84', 40], ['#e8dfaf', 30]], 31);
  c.fillStyle = '#bdb079'; c.fillRect(0, 4, 16, 1); c.fillRect(0, 11, 16, 1);
});
paint('rs_dust', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#8a1b10'; c.fillRect(6, 0, 4, 16); c.fillRect(0, 6, 16, 4);
  c.fillStyle = '#b02a18'; c.fillRect(7, 0, 2, 16); c.fillRect(0, 7, 16, 2);
});
paint('rs_block', (c) => speckle(c, '#b5251a', [['#9a1f15', 50], ['#d0382a', 40]], 41));
paint('rs_torch', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 7, 2, 8);
  c.fillStyle = '#ff3b22'; c.fillRect(6, 3, 4, 4); c.fillStyle = '#ff8a6a'; c.fillRect(7, 4, 2, 2);
});
paint('rs_torch_off', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 7, 2, 8);
  c.fillStyle = '#7a261a'; c.fillRect(6, 3, 4, 4);
});
paint('lever', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#888'; c.fillRect(5, 11, 6, 4);           // base
  c.fillStyle = '#9c7a47'; c.save(); c.translate(8, 11); c.rotate(0.5); c.fillRect(-1, -8, 2, 8); c.restore();
});
paint('lever_on', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#888'; c.fillRect(5, 11, 6, 4);
  c.fillStyle = '#9c7a47'; c.save(); c.translate(8, 11); c.rotate(-0.5); c.fillRect(-1, -8, 2, 8); c.restore();
});
paint('button', (c) => { c.clearRect(0, 0, 16, 16); c.fillStyle = '#9a9a9a'; c.fillRect(5, 6, 6, 4); });
paint('button_on', (c) => { c.clearRect(0, 0, 16, 16); c.fillStyle = '#7a7a7a'; c.fillRect(5, 7, 6, 2); });
paint('lamp', (c) => { speckle(c, '#6a5a3a', [['#5a4a2e', 40]], 51); c.strokeStyle = '#403422'; c.strokeRect(2.5, 2.5, 11, 11); });
paint('lamp_on', (c) => {
  speckle(c, '#f0c860', [['#ffe9a0', 50], ['#d8a93a', 30]], 51);
  c.strokeStyle = '#b07a2a'; c.strokeRect(2.5, 2.5, 11, 11);
});
paint('repeater', (c) => {
  speckle(c, '#9a9a9a', [['#8a8a8a', 30]], 13);
  c.fillStyle = '#7a261a'; c.fillRect(7, 2, 2, 12);
  c.fillStyle = '#5a5a5a'; c.fillRect(3, 4, 2, 2); c.fillRect(11, 9, 2, 2);
});
paint('repeater_on', (c) => {
  speckle(c, '#9a9a9a', [['#8a8a8a', 30]], 13);
  c.fillStyle = '#ff3b22'; c.fillRect(7, 2, 2, 12);
  c.fillStyle = '#5a5a5a'; c.fillRect(3, 4, 2, 2); c.fillRect(11, 9, 2, 2);
});
paint('piston_top', (c) => { speckle(c, '#9a8a6a', [['#86764e', 40]], 17); c.fillStyle = '#5c4a2e'; c.fillRect(2, 2, 12, 12); c.fillStyle = '#7a6440'; c.fillRect(3, 3, 10, 10); });
paint('piston_side', (c) => { speckle(c, '#9a8a6a', [['#86764e', 40]], 19); c.fillStyle = '#6b4f2f'; c.fillRect(0, 0, 16, 3); c.fillStyle = '#5c4a2e'; for (let y = 4; y < 16; y += 4) c.fillRect(0, y, 16, 1); });
paint('piston_face', (c) => { speckle(c, '#caa86a', [['#b89456', 40]], 23); c.fillStyle = '#8a6a3f'; c.fillRect(2, 2, 12, 12); });
paint('piston_face_sticky', (c) => { speckle(c, '#caa86a', [['#b89456', 40]], 23); c.fillStyle = '#6fae4a'; c.fillRect(2, 2, 12, 12); c.fillStyle = '#5a9a38'; c.fillRect(5, 5, 6, 6); });
paint('piston_head', (c) => { c.fillStyle = '#caa86a'; c.fillRect(0, 0, 16, 16); c.fillStyle = '#8a6a3f'; c.fillRect(0, 6, 16, 4); });
paint('comparator', (c) => {
  speckle(c, '#b0b0b0', [['#9c9c9c', 30]], 13);
  c.fillStyle = '#7a261a'; c.fillRect(7, 2, 2, 3);          // front torch
  c.fillStyle = '#7a261a'; c.fillRect(3, 11, 2, 3); c.fillRect(11, 11, 2, 3);  // side torches
});
paint('comparator_on', (c) => {
  speckle(c, '#b0b0b0', [['#9c9c9c', 30]], 13);
  c.fillStyle = '#ff3b22'; c.fillRect(7, 2, 2, 3);
  c.fillStyle = '#ff3b22'; c.fillRect(3, 11, 2, 3); c.fillRect(11, 11, 2, 3);
});
paint('aether_portal', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(150,220,255,0.55)'; c.fillRect(0, 0, 16, 16);
  let r = 73;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  c.fillStyle = 'rgba(220,245,255,0.85)';
  for (let i = 0; i < 24; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  c.fillStyle = 'rgba(120,180,240,0.7)';
  for (let i = 0; i < 16; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});
paint('chest_top', (c) => {
  speckle(c, '#9a6b34', [['#86592a', 30]], 83);
  c.strokeStyle = '#5c3d1c'; c.lineWidth = 1; c.strokeRect(1.5, 1.5, 13, 13);
  c.fillStyle = '#3a2812'; c.fillRect(7, 1, 2, 3);
});
paint('chest_side', (c) => {
  speckle(c, '#9a6b34', [['#86592a', 30], ['#a8773c', 24]], 85);
  c.strokeStyle = '#5c3d1c'; c.lineWidth = 1;
  c.strokeRect(1.5, 1.5, 13, 13); c.beginPath(); c.moveTo(1, 6); c.lineTo(15, 6); c.stroke();
  c.fillStyle = '#d8b24a'; c.fillRect(7, 6, 2, 4); c.fillStyle = '#3a2812'; c.fillRect(7, 7, 2, 2);
});
paint('torch', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 6, 2, 9);       // stick
  c.fillStyle = '#3a2c19'; c.fillRect(7, 12, 2, 3);
  c.fillStyle = '#ffcf4a'; c.fillRect(6, 3, 4, 4);        // flame
  c.fillStyle = '#fff3b0'; c.fillRect(7, 4, 2, 2);
});
paint('furnace_top', (c) => {
  speckle(c, '#7c7c7c', [['#6a6a6a', 40], ['#8c8c8c', 30]], 71);
  c.strokeStyle = '#555'; c.lineWidth = 1; c.strokeRect(3.5, 3.5, 9, 9);
  c.fillStyle = '#3a3a3a'; c.fillRect(6, 6, 4, 4);
});
paint('furnace_side', (c) => {
  speckle(c, '#7c7c7c', [['#6a6a6a', 40], ['#8c8c8c', 30]], 73);
  // dark fire opening with a glow at the bottom
  c.fillStyle = '#2a2a2a'; c.fillRect(4, 7, 8, 6);
  c.fillStyle = '#1a1a1a'; c.fillRect(5, 8, 6, 4);
  c.fillStyle = '#e2731a'; c.fillRect(5, 11, 6, 1);
  c.fillStyle = '#555'; c.fillRect(3, 3, 10, 1);
});
paint('portal', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(120,40,200,0.55)'; c.fillRect(0, 0, 16, 16);
  let r = 71;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  c.fillStyle = 'rgba(180,110,240,0.8)';
  for (let i = 0; i < 26; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  c.fillStyle = 'rgba(90,20,150,0.7)';
  for (let i = 0; i < 18; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});

// Block -> face tiles. Single name, or [top, side, bottom].
const FACES = {
  [BLOCK.GRASS]: ['grass_top', 'grass_side', 'dirt'],
  [BLOCK.DIRT]: 'dirt',
  [BLOCK.STONE]: 'stone',
  [BLOCK.COBBLE]: 'cobble',
  [BLOCK.MOSSY_COBBLE]: 'mossy',
  [BLOCK.STONE_BRICK]: 'stonebrick',
  [BLOCK.SAND]: 'sand',
  [BLOCK.GRAVEL]: 'gravel',
  [BLOCK.WOOD]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.WOOD_X]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.WOOD_Z]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.LEAVES]: 'leaves',
  [BLOCK.PLANK]: 'plank',
  [BLOCK.WATER]: 'water',
  [BLOCK.LAVA]: 'lava',
  [BLOCK.BEDROCK]: 'bedrock',
  [BLOCK.GLASS]: 'glass',
  [BLOCK.BRICK]: 'brick',
  [BLOCK.SNOW]: 'snow',
  [BLOCK.COAL_ORE]: 'coal_ore',
  [BLOCK.IRON_ORE]: 'iron_ore',
  [BLOCK.GOLD_ORE]: 'gold_ore',
  [BLOCK.DIAMOND_ORE]: 'diamond_ore',
  [BLOCK.OBSIDIAN]: 'obsidian',
  [BLOCK.NETHERRACK]: 'netherrack',
  [BLOCK.GLOWSTONE]: 'glowstone',
  [BLOCK.PORTAL]: 'portal',
  [BLOCK.CRAFTING_TABLE]: ['craft_top', 'craft_side', 'plank'],
  [BLOCK.FURNACE]: ['furnace_top', 'furnace_side', 'furnace_top'],
  [BLOCK.TORCH]: 'torch',
  [BLOCK.FARMLAND]: ['farmland', 'dirt', 'dirt'],
  [BLOCK.WHEAT0]: 'wheat0',
  [BLOCK.WHEAT1]: 'wheat1',
  [BLOCK.WHEAT2]: 'wheat2',
  [BLOCK.CHEST]: ['chest_top', 'chest_side', 'chest_top'],
  [BLOCK.SAPLING]: 'sapling',
  [BLOCK.TALL_GRASS]: 'tallgrass',
  [BLOCK.FARMLAND_WET]: ['farmland_wet', 'dirt', 'dirt'],
  [BLOCK.BED]: ['bed_top', 'bed_side', 'dirt'],
  [BLOCK.WOOL]: 'wool',
  [BLOCK.AETHER_GRASS]: ['aether_grass', 'aether_grass', 'dirt'],
  [BLOCK.AETHER_PORTAL]: 'aether_portal',
  [BLOCK.SANDSTONE]: 'sandstone',
  [BLOCK.REDSTONE_DUST]: 'rs_dust',
  [BLOCK.REDSTONE_BLOCK]: 'rs_block',
  [BLOCK.REDSTONE_TORCH]: 'rs_torch',
  [BLOCK.REDSTONE_TORCH_OFF]: 'rs_torch_off',
  [BLOCK.LEVER]: 'lever', [BLOCK.LEVER_ON]: 'lever_on',
  [BLOCK.BUTTON]: 'button', [BLOCK.BUTTON_ON]: 'button_on',
  [BLOCK.REDSTONE_LAMP]: 'lamp', [BLOCK.REDSTONE_LAMP_ON]: 'lamp_on',
  [BLOCK.REPEATER]: 'repeater', [BLOCK.REPEATER_ON]: 'repeater_on',
  [BLOCK.PISTON]: ['piston_face', 'piston_side', 'piston_side'],
  [BLOCK.PISTON_STICKY]: ['piston_face_sticky', 'piston_side', 'piston_side'],
  [BLOCK.PISTON_HEAD]: 'piston_head',
  [BLOCK.COMPARATOR]: 'comparator', [BLOCK.COMPARATOR_ON]: 'comparator_on',
};
for (const [id, tile] of WOOL_COLORS) FACES[id] = tile;

// Oriented logs: which axis shows the "ring" end-grain.
const LOGS = {
  [BLOCK.WOOD]:   { axis: 'y', ring: 'wood_top', bark: 'wood_side' },
  [BLOCK.WOOD_X]: { axis: 'x', ring: 'wood_top', bark: 'wood_side' },
  [BLOCK.WOOD_Z]: { axis: 'z', ring: 'wood_top', bark: 'wood_side' },
};

// Block metadata used by gameplay / rendering.
const BLOCK_INFO = {
  [BLOCK.GRASS]:  { name: 'Grass',       solid: true,  color: '#5fa83d' },
  [BLOCK.DIRT]:   { name: 'Dirt',        solid: true,  color: '#7a5a3a' },
  [BLOCK.STONE]:  { name: 'Stone',       solid: true,  color: '#888888' },
  [BLOCK.COBBLE]: { name: 'Cobblestone', solid: true,  color: '#7c7c7c' },
  [BLOCK.MOSSY_COBBLE]: { name: 'Mossy Cobble', solid: true, color: '#6e7a5c' },
  [BLOCK.STONE_BRICK]: { name: 'Stone Bricks', solid: true, color: '#8a8a8a' },
  [BLOCK.SAND]:   { name: 'Sand',        solid: true,  color: '#dcd29a' },
  [BLOCK.GRAVEL]: { name: 'Gravel',      solid: true,  color: '#9a938c' },
  [BLOCK.WOOD]:   { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.WOOD_X]: { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.WOOD_Z]: { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.LEAVES]: { name: 'Leaves',      solid: true,  color: '#3f8f33', transparent: true },
  [BLOCK.PLANK]:  { name: 'Planks',      solid: true,  color: '#b08a52' },
  [BLOCK.WATER]:  { name: 'Water',       solid: false, color: '#2b6fd6', transparent: true, liquid: true },
  [BLOCK.LAVA]:   { name: 'Lava',        solid: false, color: '#e2541a', transparent: true, liquid: true, hot: true, emit: 12 },
  [BLOCK.BEDROCK]:{ name: 'Bedrock',     solid: true,  color: '#3a3a3a', unbreakable: true },
  [BLOCK.GLASS]:  { name: 'Glass',       solid: true,  color: '#bfe0ec', transparent: true },
  [BLOCK.BRICK]:  { name: 'Bricks',      solid: true,  color: '#a44a3a' },
  [BLOCK.SNOW]:   { name: 'Snow',        solid: true,  color: '#f2f7fb' },
  [BLOCK.COAL_ORE]:    { name: 'Coal Ore',    solid: true, color: '#888888' },
  [BLOCK.IRON_ORE]:    { name: 'Iron Ore',    solid: true, color: '#888888' },
  [BLOCK.GOLD_ORE]:    { name: 'Gold Ore',    solid: true, color: '#888888' },
  [BLOCK.DIAMOND_ORE]: { name: 'Diamond Ore', solid: true, color: '#888888' },
  [BLOCK.OBSIDIAN]:    { name: 'Obsidian',    solid: true, color: '#15101f' },
  [BLOCK.NETHERRACK]:  { name: 'Netherrack',  solid: true, color: '#5e2a2a' },
  [BLOCK.GLOWSTONE]:   { name: 'Glowstone',   solid: true, color: '#d8a93a', emit: 15 },
  [BLOCK.PORTAL]:      { name: 'Nether Portal', solid: false, color: '#7a28c8', transparent: true, portal: true, emit: 6 },
  [BLOCK.CRAFTING_TABLE]: { name: 'Crafting Table', solid: true, color: '#9c7a47' },
  [BLOCK.FURNACE]: { name: 'Furnace', solid: true, color: '#7c7c7c' },
  [BLOCK.TORCH]:   { name: 'Torch', solid: false, color: '#ffcf6b', transparent: true, emit: 14 },
  [BLOCK.FARMLAND]: { name: 'Farmland', solid: true, color: '#5a3d24' },
  [BLOCK.WHEAT0]:  { name: 'Wheat', solid: false, color: '#5fa83d', transparent: true, crop: true },
  [BLOCK.WHEAT1]:  { name: 'Wheat', solid: false, color: '#5a9a35', transparent: true, crop: true },
  [BLOCK.WHEAT2]:  { name: 'Wheat', solid: false, color: '#c8a93a', transparent: true, crop: true },
  [BLOCK.CHEST]:   { name: 'Chest', solid: true, color: '#9a6b34' },
  [BLOCK.SAPLING]: { name: 'Sapling', solid: false, color: '#3f8f33', transparent: true, crop: true },
  [BLOCK.TALL_GRASS]: { name: 'Tall Grass', solid: false, color: '#5fa83d', transparent: true, crop: true },
  [BLOCK.FARMLAND_WET]: { name: 'Wet Farmland', solid: true, color: '#3a2a16' },
  [BLOCK.BED]: { name: 'Bed', solid: true, color: '#c0392b' },
  [BLOCK.WOOL]: { name: 'Wool', solid: true, color: '#ececec' },
  [BLOCK.AETHER_GRASS]: { name: 'Aether Grass', solid: true, color: '#9fe0c0' },
  [BLOCK.AETHER_PORTAL]: { name: 'Aether Portal', solid: false, color: '#96dcff', transparent: true, portal: true, emit: 8 },
  [BLOCK.SANDSTONE]: { name: 'Sandstone', solid: true, color: '#dcd29a' },
  // redstone (rs:true makes a non-solid component targetable + alpha-rendered)
  [BLOCK.REDSTONE_DUST]: { name: 'Redstone Dust', solid: false, transparent: true, rs: true, color: '#b02a18' },
  [BLOCK.REDSTONE_BLOCK]: { name: 'Redstone Block', solid: true, color: '#b5251a' },
  [BLOCK.REDSTONE_TORCH]: { name: 'Redstone Torch', solid: false, transparent: true, rs: true, color: '#ff3b22', emit: 7 },
  [BLOCK.REDSTONE_TORCH_OFF]: { name: 'Redstone Torch', solid: false, transparent: true, rs: true, color: '#7a261a' },
  [BLOCK.LEVER]: { name: 'Lever', solid: false, transparent: true, rs: true, color: '#9c7a47' },
  [BLOCK.LEVER_ON]: { name: 'Lever', solid: false, transparent: true, rs: true, color: '#9c7a47' },
  [BLOCK.BUTTON]: { name: 'Button', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.BUTTON_ON]: { name: 'Button', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.REDSTONE_LAMP]: { name: 'Redstone Lamp', solid: true, color: '#6a5a3a' },
  [BLOCK.REDSTONE_LAMP_ON]: { name: 'Redstone Lamp', solid: true, color: '#f0c860', emit: 15 },
  [BLOCK.REPEATER]: { name: 'Repeater', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.REPEATER_ON]: { name: 'Repeater', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.PISTON]: { name: 'Piston', solid: true, color: '#9a8a6a' },
  [BLOCK.PISTON_STICKY]: { name: 'Sticky Piston', solid: true, color: '#9a8a6a' },
  [BLOCK.PISTON_HEAD]: { name: 'Piston Head', solid: true, color: '#caa86a' },
  [BLOCK.COMPARATOR]: { name: 'Comparator', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.COMPARATOR_ON]: { name: 'Comparator', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
};
// redstone helper sets
const RS_COMPONENT = new Set([
  BLOCK.REDSTONE_DUST, BLOCK.REDSTONE_BLOCK, BLOCK.REDSTONE_TORCH, BLOCK.REDSTONE_TORCH_OFF,
  BLOCK.LEVER, BLOCK.LEVER_ON, BLOCK.BUTTON, BLOCK.BUTTON_ON,
  BLOCK.REDSTONE_LAMP, BLOCK.REDSTONE_LAMP_ON, BLOCK.REPEATER, BLOCK.REPEATER_ON,
  BLOCK.PISTON, BLOCK.PISTON_STICKY,
]);
for (const [id, , color, name] of WOOL_COLORS) BLOCK_INFO[id] = { name, solid: true, color };

// light emitted by a block (0-15)
function blockEmit(id) { const i = BLOCK_INFO[id]; return (i && i.emit) || 0; }
// does light pass through this block?
function lightPasses(id) { return id === BLOCK.AIR || (BLOCK_INFO[id] && BLOCK_INFO[id].transparent); }

// ---- mining: hardness (seconds by hand), preferred tool, drop gating ----
const HARDNESS = {
  default: 0.6,
  [BLOCK.LEAVES]: 0.2, [BLOCK.GLASS]: 0.3, [BLOCK.SNOW]: 0.4, [BLOCK.TORCH]: 0.05,
  [BLOCK.DIRT]: 0.6, [BLOCK.GRASS]: 0.6, [BLOCK.SAND]: 0.5, [BLOCK.GRAVEL]: 0.6,
  [BLOCK.FARMLAND]: 0.6, [BLOCK.FARMLAND_WET]: 0.6, [BLOCK.WHEAT0]: 0.05, [BLOCK.WHEAT1]: 0.05, [BLOCK.WHEAT2]: 0.05,
  [BLOCK.SAPLING]: 0.05, [BLOCK.TALL_GRASS]: 0.02, [BLOCK.BED]: 0.4, [BLOCK.WOOL]: 0.4,
  [BLOCK.AETHER_GRASS]: 0.6,
  [BLOCK.WOOD]: 1.6, [BLOCK.WOOD_X]: 1.6, [BLOCK.WOOD_Z]: 1.6, [BLOCK.PLANK]: 1.6, [BLOCK.CRAFTING_TABLE]: 1.6, [BLOCK.CHEST]: 1.6,
  [BLOCK.STONE]: 2.2, [BLOCK.COBBLE]: 2.2, [BLOCK.MOSSY_COBBLE]: 2.2, [BLOCK.STONE_BRICK]: 2.2, [BLOCK.BRICK]: 2.2,
  [BLOCK.FURNACE]: 3.5,
  [BLOCK.COAL_ORE]: 3, [BLOCK.IRON_ORE]: 3, [BLOCK.GOLD_ORE]: 3, [BLOCK.DIAMOND_ORE]: 3,
  [BLOCK.NETHERRACK]: 0.8, [BLOCK.GLOWSTONE]: 0.5, [BLOCK.OBSIDIAN]: 9,
};
function blockHardness(id) {
  const i = BLOCK_INFO[id];
  if (!i) return 0;
  if (i.unbreakable) return Infinity;
  return HARDNESS[id] != null ? HARDNESS[id] : HARDNESS.default;
}
// Which tool type mines a block fastest.
const BLOCK_TOOL = {
  [BLOCK.STONE]: 'pickaxe', [BLOCK.COBBLE]: 'pickaxe', [BLOCK.MOSSY_COBBLE]: 'pickaxe',
  [BLOCK.STONE_BRICK]: 'pickaxe', [BLOCK.BRICK]: 'pickaxe',
  [BLOCK.COAL_ORE]: 'pickaxe', [BLOCK.IRON_ORE]: 'pickaxe', [BLOCK.GOLD_ORE]: 'pickaxe',
  [BLOCK.DIAMOND_ORE]: 'pickaxe', [BLOCK.OBSIDIAN]: 'pickaxe',
  [BLOCK.NETHERRACK]: 'pickaxe', [BLOCK.GLOWSTONE]: 'pickaxe',
  [BLOCK.FURNACE]: 'pickaxe',
  [BLOCK.WOOD]: 'axe', [BLOCK.WOOD_X]: 'axe', [BLOCK.WOOD_Z]: 'axe',
  [BLOCK.PLANK]: 'axe', [BLOCK.CRAFTING_TABLE]: 'axe', [BLOCK.CHEST]: 'axe',
  [BLOCK.DIRT]: 'shovel', [BLOCK.GRASS]: 'shovel', [BLOCK.SAND]: 'shovel',
  [BLOCK.GRAVEL]: 'shovel', [BLOCK.SNOW]: 'shovel',
};
// Blocks that only drop an item when mined with the correct (pickaxe) tool.
const NEEDS_TOOL = new Set([
  BLOCK.STONE, BLOCK.COBBLE, BLOCK.MOSSY_COBBLE, BLOCK.STONE_BRICK, BLOCK.BRICK,
  BLOCK.COAL_ORE, BLOCK.IRON_ORE, BLOCK.GOLD_ORE, BLOCK.DIAMOND_ORE, BLOCK.OBSIDIAN,
  BLOCK.FURNACE,
]);

// Blocks offered in the build palette / inventory.
const PALETTE = [
  BLOCK.GRASS, BLOCK.DIRT, BLOCK.STONE, BLOCK.COBBLE, BLOCK.MOSSY_COBBLE, BLOCK.STONE_BRICK,
  BLOCK.SAND, BLOCK.GRAVEL, BLOCK.WOOD, BLOCK.PLANK, BLOCK.CRAFTING_TABLE, BLOCK.FURNACE, BLOCK.CHEST, BLOCK.LEAVES,
  BLOCK.GLASS, BLOCK.BRICK, BLOCK.SNOW,
  BLOCK.COAL_ORE, BLOCK.IRON_ORE, BLOCK.GOLD_ORE, BLOCK.DIAMOND_ORE,
  BLOCK.OBSIDIAN, BLOCK.NETHERRACK, BLOCK.GLOWSTONE, BLOCK.TORCH, BLOCK.BED, BLOCK.WOOL, BLOCK.SANDSTONE,
  BLOCK.REDSTONE_DUST, BLOCK.REDSTONE_BLOCK, BLOCK.REDSTONE_TORCH, BLOCK.LEVER, BLOCK.BUTTON,
  BLOCK.REDSTONE_LAMP, BLOCK.REPEATER, BLOCK.COMPARATOR, BLOCK.PISTON, BLOCK.PISTON_STICKY,
];

// ---- atlas + icons ----
let _atlas = null, _tileUV = null, _icons = {};

function _iconTile(blockId) {
  if (blockId === BLOCK.GRASS) return 'grass_top';
  const log = LOGS[blockId];
  if (log) return log.bark;
  const f = FACES[blockId];
  return Array.isArray(f) ? f[1] : f;
}

function buildAtlas() {
  if (_atlas) return { texture: _atlas, tileUV: _tileUV };
  const TS = 16;
  const cols = Math.ceil(Math.sqrt(tileOrder.length));
  const rows = Math.ceil(tileOrder.length / cols);
  const canvas = document.createElement('canvas');
  canvas.width = cols * TS; canvas.height = rows * TS;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;

  _tileUV = {};
  tileOrder.forEach((name, i) => {
    const cx = (i % cols) * TS, cy = ((i / cols) | 0) * TS;
    const tc = document.createElement('canvas'); tc.width = TS; tc.height = TS;
    const tctx = tc.getContext('2d'); tctx.imageSmoothingEnabled = false;
    TILE[name](tctx);
    ctx.drawImage(tc, cx, cy);
    const pad = 0.05;
    _tileUV[name] = [
      (cx + pad) / canvas.width, 1 - (cy + TS - pad) / canvas.height,
      (cx + TS - pad) / canvas.width, 1 - (cy + pad) / canvas.height,
    ];
    TILE[name]._canvas = tc;   // keep for icon export
  });

  // build per-block icon data URLs for every renderable block (scaled up, crisp)
  for (const id of Object.keys(FACES).map(Number)) {
    const tile = _iconTile(id);
    const ic = document.createElement('canvas'); ic.width = 32; ic.height = 32;
    const ictx = ic.getContext('2d'); ictx.imageSmoothingEnabled = false;
    ictx.drawImage(TILE[tile]._canvas, 0, 0, 32, 32);
    _icons[id] = ic.toDataURL ? ic.toDataURL() : '';
  }

  const tex = new THREE.CanvasTexture(canvas);
  tex.magFilter = THREE.NearestFilter; tex.minFilter = THREE.NearestFilter;
  tex.generateMipmaps = false; tex.colorSpace = THREE.SRGBColorSpace;
  _atlas = tex;
  return { texture: _atlas, tileUV: _tileUV };
}

// UV rect for a face. `face` is one of 'py','ny','px','nx','pz','nz'.
function faceUV(blockId, face) {
  const log = LOGS[blockId];
  if (log) {
    const axis = face[1];                       // 'y' from 'py', 'x' from 'nx', etc.
    return _tileUV[axis === log.axis ? log.ring : log.bark];
  }
  const f = FACES[blockId];
  if (Array.isArray(f)) return _tileUV[face === 'py' ? f[0] : face === 'ny' ? f[2] : f[1]];
  return _tileUV[f];
}

function blockIcon(blockId) { return _icons[blockId] || ''; }
