// Block definitions, procedural texture atlas, oriented logs, and item icons.
// THREE is a global provided by the engine bridge in index.html.

// Block IDs. 0 is always AIR.
const BLOCK = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  SAND: 4,
  WOOD: 5,        // vertical log (Y axis)
  LEAVES: 6,
  PLANK: 7,
  WATER: 8,
  BEDROCK: 9,
  GLASS: 10,
  BRICK: 11,
  COBBLE: 12,
  SNOW: 13,
  GRAVEL: 14,
  COAL_ORE: 15,
  IRON_ORE: 16,
  GOLD_ORE: 17,
  DIAMOND_ORE: 18,
  OBSIDIAN: 19,
  NETHERRACK: 20,
  GLOWSTONE: 21,
  LAVA: 22,
  PORTAL: 23,
  STONE_BRICK: 24,
  MOSSY_COBBLE: 25,
  WOOD_X: 26,     // log lying along X
  WOOD_Z: 27,     // log lying along Z
  CRAFTING_TABLE: 28,
  FURNACE: 29,
  TORCH: 30,
  FARMLAND: 31,
  WHEAT0: 32,    // seedling
  WHEAT1: 33,    // growing
  WHEAT2: 34,    // mature
  CHEST: 35,
  SAPLING: 36,
  TALL_GRASS: 37,
  FARMLAND_WET: 38,
  BED: 39,
  WOOL: 40,
  WOOL_RED: 41, WOOL_ORANGE: 42, WOOL_YELLOW: 43, WOOL_LIME: 44, WOOL_GREEN: 45,
  WOOL_CYAN: 46, WOOL_BLUE: 47, WOOL_PURPLE: 48, WOOL_PINK: 49, WOOL_BLACK: 50,
  AETHER_PORTAL: 51,
  AETHER_GRASS: 52,
  SANDSTONE: 53,
  // redstone
  REDSTONE_DUST: 54, REDSTONE_BLOCK: 55,
  REDSTONE_TORCH: 56, REDSTONE_TORCH_OFF: 57,
  LEVER: 58, LEVER_ON: 59,
  BUTTON: 60, BUTTON_ON: 61,
  REDSTONE_LAMP: 62, REDSTONE_LAMP_ON: 63,
  REPEATER: 64, REPEATER_ON: 65,
  PISTON: 66, PISTON_STICKY: 67, PISTON_HEAD: 68,
  COMPARATOR: 69, COMPARATOR_ON: 70,
  // The End + structures
  END_STONE: 71,
  END_PORTAL_FRAME: 72,
  END_PORTAL_FRAME_EYE: 73,
  END_PORTAL: 74,
  DRAGON_EGG: 75,
  NETHER_BRICK: 76,
  // Create-style kinetics (rotational power)
  ANDESITE_CASING: 77,
  BRASS_CASING: 78,
  SHAFT: 79,
  COGWHEEL: 80,
  LARGE_COGWHEEL: 81,
  GEARBOX: 82,
  WATER_WHEEL: 83,
  HAND_CRANK: 84,
  MILLSTONE: 85,
  MECHANICAL_PRESS: 86,
  ENCASED_FAN: 87,
  CREATIVE_MOTOR: 88,
  // building blocks (rendered as partial shapes)
  SLAB_STONE: 89, SLAB_COBBLE: 90, SLAB_PLANK: 91, SLAB_BRICK: 92,
  STAIRS_STONE: 93, STAIRS_COBBLE: 94, STAIRS_PLANK: 95, STAIRS_BRICK: 96,
  FENCE: 97, GLASS_PANE: 98,
  // high range (240..255) — keeps the 0..99 block range from colliding with items
  LADDER: 240, DOOR: 241, TRAPDOOR: 242,
};

// Each tile is generated by a painter function onto a 16x16 canvas.
const TILE = {};
let tileOrder = [];
function paint(name, fn) { TILE[name] = fn; tileOrder.push(name); }

// ---- texture helpers ----
function _toRGB(hex) { const n = parseInt(hex.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; }
function _cl(v) { return v < 0 ? 0 : v > 255 ? 255 : v | 0; }
function _rgb(r, g, b) { return 'rgb(' + (r | 0) + ',' + (g | 0) + ',' + (b | 0) + ')'; }
// small deterministic xorshift PRNG (one per tile, by seed)
function _prng(seed) {
  let r = (seed * 1973 + 9277) >>> 0 || 1;
  return () => { r ^= r << 13; r >>>= 0; r ^= r >> 17; r ^= r << 5; r >>>= 0; return r / 4294967296; };
}

// Base + per-pixel value noise (Minecraft's grainy look), then optional accent
// spots. `spots` is a list of [color, count]. `grain` controls noise strength.
function speckle(ctx, base, spots, seed = 1, grain = 13) {
  const [br, bg, bb] = _toRGB(base);
  const rnd = _prng(seed);
  for (let y = 0; y < 16; y++)
    for (let x = 0; x < 16; x++) {
      const d = (rnd() * 2 - 1) * grain;
      ctx.fillStyle = _rgb(_cl(br + d), _cl(bg + d), _cl(bb + d));
      ctx.fillRect(x, y, 1, 1);
    }
  for (const [color, amount] of spots) {
    ctx.fillStyle = color;
    for (let i = 0; i < amount; i++) ctx.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  }
}
// Ore nuggets: scattered mineral clusters with a highlight + shadow pixel for depth.
function blobs(ctx, color, count, seed, hi, lo) {
  const rnd = _prng(seed * 7 + 3);
  const [r, g, b] = _toRGB(color);
  hi = hi || _rgb(_cl(r + 55), _cl(g + 55), _cl(b + 55));
  lo = lo || _rgb(_cl(r - 45), _cl(g - 45), _cl(b - 45));
  for (let i = 0; i < count; i++) {
    const x = 1 + (rnd() * 12 | 0), y = 1 + (rnd() * 12 | 0);
    ctx.fillStyle = lo; ctx.fillRect(x, y, 3, 3);
    ctx.fillStyle = color; ctx.fillRect(x, y, 2, 2);
    ctx.fillStyle = hi; ctx.fillRect(x, y, 1, 1);
    if (rnd() > 0.5) { ctx.fillStyle = color; ctx.fillRect(x + 2, y + 2, 1, 1); }
  }
}

paint('grass_top', (c) => speckle(c, '#62a23e', [['#71b94a', 46], ['#558f35', 40], ['#7ccb52', 22], ['#4c8530', 18]], 3, 12));
paint('grass_side', (c) => {
  speckle(c, '#79573a', [['#6a4c30', 40], ['#8a6a44', 30], ['#5e4329', 20]], 5, 12);
  // grassy top band with an irregular fringe dripping down the dirt
  c.fillStyle = '#62a23e'; c.fillRect(0, 0, 16, 4);
  const rnd = _prng(57);
  for (let x = 0; x < 16; x++) {
    c.fillStyle = (rnd() < 0.5) ? '#558f35' : '#71b94a';
    c.fillRect(x, 0, 1, 1);
    const drip = 3 + (rnd() * 3 | 0);
    c.fillStyle = '#4c8530';
    c.fillRect(x, 4, 1, drip - 3);
  }
});
paint('dirt', (c) => speckle(c, '#79573a', [['#6a4c30', 46], ['#8a6a44', 36], ['#5e4329', 22]], 7, 13));
paint('stone', (c) => speckle(c, '#848484', [['#777777', 40], ['#949494', 34], ['#6c6c6c', 22]], 11, 11));
paint('cobble', (c) => {
  speckle(c, '#7d7d7d', [['#8f8f8f', 22], ['#6c6c6c', 20]], 13, 16);
  // dark mortar between irregular cobbles
  c.fillStyle = '#4e4e4e';
  c.fillRect(0, 4, 16, 1); c.fillRect(0, 10, 16, 1);
  c.fillRect(6, 0, 1, 4); c.fillRect(11, 0, 1, 4);
  c.fillRect(3, 5, 1, 5); c.fillRect(9, 5, 1, 5); c.fillRect(13, 5, 1, 5);
  c.fillRect(6, 11, 1, 5); c.fillRect(11, 11, 1, 5);
  // lit pebble tops
  c.fillStyle = '#9c9c9c';
  c.fillRect(1, 1, 3, 2); c.fillRect(8, 1, 2, 2); c.fillRect(12, 1, 2, 2);
  c.fillRect(1, 6, 2, 3); c.fillRect(10, 6, 2, 3); c.fillRect(0, 11, 5, 3); c.fillRect(7, 12, 3, 3);
});
paint('mossy', (c) => {
  speckle(c, '#71795e', [['#828c66', 22], ['#5e6a4a', 20], ['#4a7a3a', 18]], 14, 15);
  c.fillStyle = '#454d3a';
  c.fillRect(0, 4, 16, 1); c.fillRect(0, 10, 16, 1);
  c.fillRect(6, 0, 1, 4); c.fillRect(11, 0, 1, 4);
  c.fillRect(3, 5, 1, 5); c.fillRect(9, 5, 1, 5); c.fillRect(6, 11, 1, 5);
  c.fillStyle = '#5d8a3e'; const rnd = _prng(140);   // moss patches
  for (let i = 0; i < 26; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});
paint('stonebrick', (c) => {
  speckle(c, '#828282', [['#949494', 20], ['#717171', 18]], 15, 11);
  c.fillStyle = '#5c5c5c';                 // recessed mortar
  c.fillRect(0, 7, 16, 1);
  c.fillRect(8, 0, 1, 8); c.fillRect(4, 8, 1, 8); c.fillRect(12, 8, 1, 8);
  c.fillStyle = 'rgba(255,255,255,0.07)'; // top-edge highlight on each brick
  c.fillRect(0, 0, 16, 1); c.fillRect(0, 8, 16, 1);
});
paint('sand', (c) => speckle(c, '#dcd29a', [['#d0c587', 34], ['#e8dfaf', 28], ['#c8bd80', 16]], 17, 9));
paint('gravel', (c) => {
  speckle(c, '#938c85', [['#7d766f', 30], ['#b0a89f', 24]], 18, 14);
  c.fillStyle = '#6a6460'; const rnd = _prng(181);   // dark pebbles
  for (let i = 0; i < 7; i++) { const x = rnd() * 13 | 0, y = rnd() * 13 | 0; c.fillRect(x, y, 2, 2); }
  c.fillStyle = '#c2bab1';
  for (let i = 0; i < 6; i++) c.fillRect(rnd() * 15 | 0, rnd() * 15 | 0, 1, 1);
});
paint('wood_top', (c) => {
  speckle(c, '#b9925b', [['#a87f49', 16], ['#c69f63', 14]], 19, 9);
  c.strokeStyle = '#8a6a3f'; c.lineWidth = 1;
  for (let r = 2; r <= 7; r += 2) { c.beginPath(); c.arc(8, 8, r, 0, 7); c.stroke(); }
  c.fillStyle = '#6e5230'; c.fillRect(7, 7, 2, 2);   // pith
});
paint('wood_side', (c) => {
  speckle(c, '#6b4f2f', [['#5c4327', 22], ['#7c5d39', 18]], 23, 9);
  c.fillStyle = '#4f3a22'; for (let x = 1; x < 16; x += 4) c.fillRect(x, 0, 1, 16);
  c.fillStyle = '#7e5f39'; for (let x = 3; x < 16; x += 4) c.fillRect(x, 0, 1, 16);
  c.fillStyle = '#4a3520'; c.fillRect(5, 5, 2, 2); c.fillRect(10, 10, 2, 2);   // knots
});
paint('leaves', (c) => {
  speckle(c, '#3f8f33', [['#357a2b', 64], ['#4aa53c', 56], ['#2c6624', 40], ['#58c046', 26]], 29, 17);
  c.fillStyle = '#214d1b'; const rnd = _prng(291);   // shadowed gaps between clusters
  for (let i = 0; i < 12; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});
paint('plank', (c) => {
  speckle(c, '#b08a52', [['#9e7b46', 20], ['#c49a5e', 16]], 31, 9);
  c.fillStyle = '#8a6a3f'; for (let y = 3; y < 16; y += 4) c.fillRect(0, y, 16, 1);   // plank seams
  c.fillStyle = '#9c7842';                 // short grain ticks
  for (const [x, y] of [[5, 1], [11, 1], [2, 5], [9, 5], [6, 9], [13, 9], [3, 13], [10, 13]]) c.fillRect(x, y, 1, 2);
});
paint('water', (c) => speckle(c, '#2b6fd6', [['#2461c4', 36], ['#3a80e8', 30], ['#1f57b4', 18]], 37, 8));
paint('lava', (c) => {
  speckle(c, '#e2541a', [['#ff8a2a', 40], ['#c23a10', 30]], 38, 10);
  c.fillStyle = '#ffd24a'; const rnd = _prng(382);   // bright molten blobs
  for (let i = 0; i < 8; i++) { const x = rnd() * 14 | 0, y = rnd() * 14 | 0; c.fillRect(x, y, 2, 2); }
});
paint('bedrock', (c) => speckle(c, '#3a3a3a', [['#222222', 44], ['#4c4c4c', 34], ['#171717', 24]], 41, 16));
paint('glass', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(180,220,235,0.25)'; c.fillRect(0, 0, 16, 16);
  c.strokeStyle = 'rgba(210,235,245,0.9)'; c.lineWidth = 1.5;
  c.strokeRect(1, 1, 14, 14);
  c.beginPath(); c.moveTo(3, 3); c.lineTo(7, 7); c.stroke();
});
paint('brick', (c) => {
  speckle(c, '#9e463a', [['#8c3e32', 22], ['#b05446', 16]], 43, 10);
  c.fillStyle = '#cfc7b8';                 // light mortar, running-bond
  for (let y = 0; y < 16; y += 4) c.fillRect(0, y, 16, 1);
  for (let i = 0; i < 4; i++) { const y = i * 4, off = (i % 2) ? 4 : 0; for (let x = off; x < 16; x += 8) c.fillRect(x, y, 1, 4); }
});
paint('snow', (c) => speckle(c, '#f2f7fb', [['#e4ecf3', 30], ['#ffffff', 30]], 47, 6));
const _oreBase = (c, seed) => speckle(c, '#848484', [['#949494', 18], ['#717171', 16]], seed, 11);
paint('coal_ore', (c) => { _oreBase(c, 11); blobs(c, '#232323', 6, 7, '#3a3a3a', '#101010'); });
paint('iron_ore', (c) => { _oreBase(c, 11); blobs(c, '#c8a07a', 6, 9); });
paint('gold_ore', (c) => { _oreBase(c, 11); blobs(c, '#f5d23a', 6, 13); });
paint('diamond_ore', (c) => { _oreBase(c, 11); blobs(c, '#4fe0d8', 6, 21); });
paint('obsidian', (c) => {
  speckle(c, '#15101f', [['#0c0814', 60], ['#241b36', 30], ['#3a2a55', 12]], 53);
});
paint('netherrack', (c) => speckle(c, '#5e2a2a', [['#4a1f1f', 60], ['#722f2f', 40], ['#3a1818', 24]], 59));
paint('glowstone', (c) => speckle(c, '#d8a93a', [['#f0d469', 60], ['#b07e22', 40], ['#fff0a0', 24]], 61));
paint('craft_top', (c) => {
  speckle(c, '#9c7a47', [['#8a6a3c', 30]], 67);
  c.strokeStyle = '#5c4426'; c.lineWidth = 1;
  c.strokeRect(1.5, 1.5, 13, 13); c.beginPath();
  c.moveTo(8, 2); c.lineTo(8, 14); c.moveTo(2, 8); c.lineTo(14, 8); c.stroke();
});
paint('craft_side', (c) => {
  speckle(c, '#b08a52', [['#9e7b46', 40]], 31);
  c.fillStyle = '#6b4f2f';
  c.fillRect(0, 0, 16, 4);
  for (let y = 5; y < 16; y += 4) { c.fillStyle = '#8a6a3f'; c.fillRect(0, y, 16, 1); }
  c.fillStyle = '#6b4f2f'; c.fillRect(2, 6, 3, 3); c.fillRect(9, 10, 3, 3);
});
paint('farmland', (c) => {
  speckle(c, '#5a3d24', [['#4a3119', 50], ['#6b4d30', 30]], 79);
  c.fillStyle = '#3a2814';
  c.fillRect(2, 3, 12, 2); c.fillRect(2, 8, 12, 2); c.fillRect(2, 13, 12, 1);
});
paint('wheat0', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#5fa83d';
  for (let x = 3; x < 16; x += 4) c.fillRect(x, 11, 1, 4);
});
paint('wheat1', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#5a9a35';
  for (let x = 3; x < 16; x += 4) c.fillRect(x, 6, 2, 9);
});
paint('wheat2', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#c8a93a';
  for (let x = 3; x < 16; x += 4) { c.fillRect(x, 3, 2, 12); c.fillStyle = '#e8d36a'; c.fillRect(x, 3, 2, 3); c.fillStyle = '#c8a93a'; }
});
paint('sapling', (c) => {
  c.clearRect(0, 0, 16, 16);
  // little trunk
  c.fillStyle = '#7a5736'; c.fillRect(7, 10, 2, 5);
  c.fillStyle = '#5e421f'; c.fillRect(7, 13, 2, 2);
  // leafy canopy (rounded, layered greens)
  const leaf = (x, y, w, h, col) => { c.fillStyle = col; c.fillRect(x, y, w, h); };
  leaf(5, 4, 6, 6, '#3f8f33');
  leaf(4, 6, 8, 3, '#3f8f33');
  leaf(6, 2, 4, 3, '#4aa53c');
  leaf(5, 5, 2, 2, '#56b845'); leaf(9, 7, 2, 2, '#56b845');
  leaf(7, 3, 2, 2, '#56b845');
  leaf(4, 8, 2, 1, '#2f6e26'); leaf(10, 5, 2, 1, '#2f6e26');
  leaf(8, 8, 1, 1, '#2f6e26');
});
paint('tallgrass', (c) => {
  c.clearRect(0, 0, 16, 16);
  const blade = (x, col) => { c.fillStyle = col; c.fillRect(x, 6 + ((x * 5) % 3), 1, 9 - ((x * 5) % 3)); };
  for (let x = 2; x < 15; x += 2) blade(x, x % 4 === 0 ? '#4e9a36' : '#5fa83d');
  c.fillStyle = '#6fbf48'; c.fillRect(4, 5, 1, 3); c.fillRect(10, 6, 1, 3);
});
paint('farmland_wet', (c) => {
  speckle(c, '#3a2a16', [['#2e2010', 50], ['#46331b', 30]], 79);
  c.fillStyle = '#241a0c';
  c.fillRect(2, 3, 12, 2); c.fillRect(2, 8, 12, 2); c.fillRect(2, 13, 12, 1);
  c.fillStyle = '#2b3a6a'; c.fillRect(7, 3, 2, 2);   // damp sheen
});
paint('bed_top', (c) => {
  speckle(c, '#c0392b', [['#a83226', 30]], 91);
  c.fillStyle = '#ecf0f1'; c.fillRect(2, 2, 12, 5);   // pillow
  c.strokeStyle = '#8a2a20'; c.lineWidth = 1; c.strokeRect(1.5, 1.5, 13, 13);
});
paint('bed_side', (c) => {
  speckle(c, '#c0392b', [['#a83226', 30]], 93);
  c.fillStyle = '#6b4f2f'; c.fillRect(0, 12, 16, 4);  // wooden frame
  c.fillStyle = '#ecf0f1'; c.fillRect(1, 3, 4, 4);    // pillow edge
});
paint('wool', (c) => {
  speckle(c, '#ececec', [['#dcdcdc', 50], ['#fbfbfb', 40], ['#cfcfcf', 24]], 95);
});
// colored wool (Easter-egg wool world) — painted via WOOL_COLORS loop below
const WOOL_COLORS = [
  [BLOCK.WOOL_RED, 'wool_red', '#b5342a', 'Red Wool'],
  [BLOCK.WOOL_ORANGE, 'wool_orange', '#d27a1e', 'Orange Wool'],
  [BLOCK.WOOL_YELLOW, 'wool_yellow', '#e0c12c', 'Yellow Wool'],
  [BLOCK.WOOL_LIME, 'wool_lime', '#86d12c', 'Lime Wool'],
  [BLOCK.WOOL_GREEN, 'wool_green', '#3f8f33', 'Green Wool'],
  [BLOCK.WOOL_CYAN, 'wool_cyan', '#2aa9b5', 'Cyan Wool'],
  [BLOCK.WOOL_BLUE, 'wool_blue', '#2f5fc0', 'Blue Wool'],
  [BLOCK.WOOL_PURPLE, 'wool_purple', '#8a3fc0', 'Purple Wool'],
  [BLOCK.WOOL_PINK, 'wool_pink', '#e08ab0', 'Pink Wool'],
  [BLOCK.WOOL_BLACK, 'wool_black', '#2a2a2e', 'Black Wool'],
];
for (const [, tile, color] of WOOL_COLORS) {
  const shade = (hex, d) => {
    const n = parseInt(hex.slice(1), 16);
    const r = Math.max(0, Math.min(255, ((n >> 16) & 255) + d));
    const g = Math.max(0, Math.min(255, ((n >> 8) & 255) + d));
    const b = Math.max(0, Math.min(255, (n & 255) + d));
    return '#' + ((1 << 24) | (r << 16) | (g << 8) | b).toString(16).slice(1);
  };
  paint(tile, (c) => speckle(c, color, [[shade(color, 18), 45], [shade(color, -18), 40]], 7));
}
paint('aether_grass', (c) => {
  speckle(c, '#9fe0c0', [['#b6f0d6', 50], ['#7fc8a6', 40]], 71);
});
paint('sandstone', (c) => {
  speckle(c, '#dcd29a', [['#cabd84', 40], ['#e8dfaf', 30]], 31);
  c.fillStyle = '#bdb079'; c.fillRect(0, 4, 16, 1); c.fillRect(0, 11, 16, 1);
});
paint('rs_dust', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#8a1b10'; c.fillRect(6, 0, 4, 16); c.fillRect(0, 6, 16, 4);
  c.fillStyle = '#b02a18'; c.fillRect(7, 0, 2, 16); c.fillRect(0, 7, 16, 2);
});
paint('rs_block', (c) => speckle(c, '#b5251a', [['#9a1f15', 50], ['#d0382a', 40]], 41));
paint('rs_torch', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 7, 2, 8);
  c.fillStyle = '#ff3b22'; c.fillRect(6, 3, 4, 4); c.fillStyle = '#ff8a6a'; c.fillRect(7, 4, 2, 2);
});
paint('rs_torch_off', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 7, 2, 8);
  c.fillStyle = '#7a261a'; c.fillRect(6, 3, 4, 4);
});
paint('lever', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#888'; c.fillRect(5, 11, 6, 4);           // base
  c.fillStyle = '#9c7a47'; c.save(); c.translate(8, 11); c.rotate(0.5); c.fillRect(-1, -8, 2, 8); c.restore();
});
paint('lever_on', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#888'; c.fillRect(5, 11, 6, 4);
  c.fillStyle = '#9c7a47'; c.save(); c.translate(8, 11); c.rotate(-0.5); c.fillRect(-1, -8, 2, 8); c.restore();
});
paint('button', (c) => { c.clearRect(0, 0, 16, 16); c.fillStyle = '#9a9a9a'; c.fillRect(5, 6, 6, 4); });
paint('button_on', (c) => { c.clearRect(0, 0, 16, 16); c.fillStyle = '#7a7a7a'; c.fillRect(5, 7, 6, 2); });
paint('lamp', (c) => { speckle(c, '#6a5a3a', [['#5a4a2e', 40]], 51); c.strokeStyle = '#403422'; c.strokeRect(2.5, 2.5, 11, 11); });
paint('lamp_on', (c) => {
  speckle(c, '#f0c860', [['#ffe9a0', 50], ['#d8a93a', 30]], 51);
  c.strokeStyle = '#b07a2a'; c.strokeRect(2.5, 2.5, 11, 11);
});
paint('repeater', (c) => {
  speckle(c, '#9a9a9a', [['#8a8a8a', 30]], 13);
  c.fillStyle = '#7a261a'; c.fillRect(7, 2, 2, 12);
  c.fillStyle = '#5a5a5a'; c.fillRect(3, 4, 2, 2); c.fillRect(11, 9, 2, 2);
});
paint('repeater_on', (c) => {
  speckle(c, '#9a9a9a', [['#8a8a8a', 30]], 13);
  c.fillStyle = '#ff3b22'; c.fillRect(7, 2, 2, 12);
  c.fillStyle = '#5a5a5a'; c.fillRect(3, 4, 2, 2); c.fillRect(11, 9, 2, 2);
});
paint('piston_top', (c) => { speckle(c, '#9a8a6a', [['#86764e', 40]], 17); c.fillStyle = '#5c4a2e'; c.fillRect(2, 2, 12, 12); c.fillStyle = '#7a6440'; c.fillRect(3, 3, 10, 10); });
paint('piston_side', (c) => { speckle(c, '#9a8a6a', [['#86764e', 40]], 19); c.fillStyle = '#6b4f2f'; c.fillRect(0, 0, 16, 3); c.fillStyle = '#5c4a2e'; for (let y = 4; y < 16; y += 4) c.fillRect(0, y, 16, 1); });
paint('piston_face', (c) => { speckle(c, '#caa86a', [['#b89456', 40]], 23); c.fillStyle = '#8a6a3f'; c.fillRect(2, 2, 12, 12); });
paint('piston_face_sticky', (c) => { speckle(c, '#caa86a', [['#b89456', 40]], 23); c.fillStyle = '#6fae4a'; c.fillRect(2, 2, 12, 12); c.fillStyle = '#5a9a38'; c.fillRect(5, 5, 6, 6); });
paint('piston_head', (c) => { c.fillStyle = '#caa86a'; c.fillRect(0, 0, 16, 16); c.fillStyle = '#8a6a3f'; c.fillRect(0, 6, 16, 4); });
paint('comparator', (c) => {
  speckle(c, '#b0b0b0', [['#9c9c9c', 30]], 13);
  c.fillStyle = '#7a261a'; c.fillRect(7, 2, 2, 3);          // front torch
  c.fillStyle = '#7a261a'; c.fillRect(3, 11, 2, 3); c.fillRect(11, 11, 2, 3);  // side torches
});
paint('comparator_on', (c) => {
  speckle(c, '#b0b0b0', [['#9c9c9c', 30]], 13);
  c.fillStyle = '#ff3b22'; c.fillRect(7, 2, 2, 3);
  c.fillStyle = '#ff3b22'; c.fillRect(3, 11, 2, 3); c.fillRect(11, 11, 2, 3);
});
paint('aether_portal', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(150,220,255,0.55)'; c.fillRect(0, 0, 16, 16);
  let r = 73;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  c.fillStyle = 'rgba(220,245,255,0.85)';
  for (let i = 0; i < 24; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  c.fillStyle = 'rgba(120,180,240,0.7)';
  for (let i = 0; i < 16; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});
paint('chest_top', (c) => {
  speckle(c, '#9a6b34', [['#86592a', 30]], 83);
  c.strokeStyle = '#5c3d1c'; c.lineWidth = 1; c.strokeRect(1.5, 1.5, 13, 13);
  c.fillStyle = '#3a2812'; c.fillRect(7, 1, 2, 3);
});
paint('chest_side', (c) => {
  speckle(c, '#9a6b34', [['#86592a', 30], ['#a8773c', 24]], 85);
  c.strokeStyle = '#5c3d1c'; c.lineWidth = 1;
  c.strokeRect(1.5, 1.5, 13, 13); c.beginPath(); c.moveTo(1, 6); c.lineTo(15, 6); c.stroke();
  c.fillStyle = '#d8b24a'; c.fillRect(7, 6, 2, 4); c.fillStyle = '#3a2812'; c.fillRect(7, 7, 2, 2);
});
paint('torch', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = '#6b4f2f'; c.fillRect(7, 6, 2, 9);       // stick
  c.fillStyle = '#3a2c19'; c.fillRect(7, 12, 2, 3);
  c.fillStyle = '#ffcf4a'; c.fillRect(6, 3, 4, 4);        // flame
  c.fillStyle = '#fff3b0'; c.fillRect(7, 4, 2, 2);
});
paint('furnace_top', (c) => {
  speckle(c, '#7c7c7c', [['#6a6a6a', 40], ['#8c8c8c', 30]], 71);
  c.strokeStyle = '#555'; c.lineWidth = 1; c.strokeRect(3.5, 3.5, 9, 9);
  c.fillStyle = '#3a3a3a'; c.fillRect(6, 6, 4, 4);
});
paint('furnace_side', (c) => {
  speckle(c, '#7c7c7c', [['#6a6a6a', 40], ['#8c8c8c', 30]], 73);
  // dark fire opening with a glow at the bottom
  c.fillStyle = '#2a2a2a'; c.fillRect(4, 7, 8, 6);
  c.fillStyle = '#1a1a1a'; c.fillRect(5, 8, 6, 4);
  c.fillStyle = '#e2731a'; c.fillRect(5, 11, 6, 1);
  c.fillStyle = '#555'; c.fillRect(3, 3, 10, 1);
});
paint('portal', (c) => {
  c.clearRect(0, 0, 16, 16);
  c.fillStyle = 'rgba(120,40,200,0.55)'; c.fillRect(0, 0, 16, 16);
  let r = 71;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  c.fillStyle = 'rgba(180,110,240,0.8)';
  for (let i = 0; i < 26; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  c.fillStyle = 'rgba(90,20,150,0.7)';
  for (let i = 0; i < 18; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});
// ---- The End + structure tiles ----
paint('end_stone', (c) => {
  speckle(c, '#dcdca4', [['#c9caa0', 44], ['#eef0c6', 30]], 61);
});
paint('nether_brick', (c) => {
  speckle(c, '#39202a', [['#2c181f', 34]], 62);
  c.fillStyle = '#22121a';
  c.fillRect(0, 5, 16, 1); c.fillRect(0, 11, 16, 1);
  c.fillRect(7, 0, 1, 5); c.fillRect(3, 6, 1, 5); c.fillRect(11, 12, 1, 4);
});
paint('epf_top', (c) => {
  speckle(c, '#5b6b54', [['#4c5c46', 34]], 63);
  c.fillStyle = '#2c382a'; c.fillRect(4, 4, 8, 8);          // empty eye socket
});
paint('epf_eye', (c) => {
  speckle(c, '#5b6b54', [['#4c5c46', 34]], 63);
  c.fillStyle = '#0a1c14'; c.fillRect(4, 4, 8, 8);
  c.fillStyle = '#2fae8a'; c.fillRect(6, 6, 4, 4);          // eye of ender
  c.fillStyle = '#bff0dd'; c.fillRect(7, 7, 1, 1);
});
paint('epf_side', (c) => {
  speckle(c, '#495a43', [['#3d4c39', 34]], 64);
  c.fillStyle = '#5b6b54'; c.fillRect(0, 0, 16, 5);         // lighter cap band
});
paint('dragon_egg', (c) => {
  speckle(c, '#190f24', [['#0c0714', 44], ['#291737', 28]], 66);
  c.fillStyle = '#3a2450'; c.fillRect(6, 3, 4, 2); c.fillRect(5, 7, 2, 2); c.fillRect(10, 9, 2, 2);
  c.fillStyle = '#5c3c7a'; c.fillRect(7, 4, 1, 1);
});
paint('end_portal', (c) => {
  c.fillStyle = '#070712'; c.fillRect(0, 0, 16, 16);
  let r = 99;
  const rnd = () => { r = (r * 9301 + 49297) % 233280; return r / 233280; };
  c.fillStyle = 'rgba(190,238,222,0.95)';
  for (let i = 0; i < 22; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
  c.fillStyle = 'rgba(110,184,154,0.8)';
  for (let i = 0; i < 14; i++) c.fillRect((rnd() * 16) | 0, (rnd() * 16) | 0, 1, 1);
});

// ---- Create-style kinetics tiles (andesite/brass casings, cogs, shafts) ----
function _frame(c, col) {   // a wooden casing frame around the sides
  c.fillStyle = col; c.fillRect(0, 0, 16, 2); c.fillRect(0, 14, 16, 2); c.fillRect(0, 0, 2, 16); c.fillRect(14, 0, 2, 16);
}
function _disc(c, cx, cy, r, col) { c.fillStyle = col; c.beginPath(); c.arc(cx, cy, r, 0, 7); c.fill(); }
function _gear(c, col, dark, teeth, R) {
  speckle(c, '#787b7a', [['#6a6d6c', 18], ['#86898b', 14]], teeth * 7 + 3, 8);   // opaque andesite face
  for (let i = 0; i < teeth; i++) { const a = i / teeth * Math.PI * 2; const x = 8 + Math.cos(a) * (R + 1.5), y = 8 + Math.sin(a) * (R + 1.5); c.fillStyle = dark; c.fillRect(Math.round(x) - 1, Math.round(y) - 1, 3, 3); }
  _disc(c, 8, 8, R, col); _disc(c, 8, 8, R - 1.5, dark); _disc(c, 8, 8, R - 2.5, col); _disc(c, 8, 8, 1.6, dark);
}
paint('andesite_casing', (c) => { speckle(c, '#8f9291', [['#7f8281', 22], ['#9da09f', 16]], 201, 9); _frame(c, '#9a6a3a'); c.fillStyle = '#7a5230'; c.fillRect(1, 1, 1, 14); c.fillRect(14, 1, 1, 14); });
paint('andesite_casing_top', (c) => { speckle(c, '#8f9291', [['#7f8281', 22], ['#a1a4a3', 16]], 202, 9); c.strokeStyle = '#6f7271'; c.strokeRect(2.5, 2.5, 11, 11); c.fillStyle = '#6f7271'; c.fillRect(7, 2, 2, 2); c.fillRect(7, 12, 2, 2); });
paint('brass_casing', (c) => { speckle(c, '#cba74e', [['#b8923e', 22], ['#dcb65c', 16]], 203, 9); _frame(c, '#9a6a3a'); });
paint('brass_casing_top', (c) => { speckle(c, '#cba74e', [['#b8923e', 22]], 204, 9); c.strokeStyle = '#9a7a32'; c.strokeRect(2.5, 2.5, 11, 11); c.fillStyle = '#e3c870'; c.fillRect(3, 3, 3, 3); c.fillRect(10, 10, 3, 3); });
paint('shaft_side', (c) => { speckle(c, '#74777a', [['#65686c', 16]], 230, 8); c.fillStyle = '#8c8f8e'; c.fillRect(0, 5, 16, 6); c.fillStyle = '#a2a5a4'; c.fillRect(0, 6, 16, 1); c.fillStyle = '#6f7271'; c.fillRect(0, 10, 16, 1); c.fillStyle = '#5f6261'; for (let x = 2; x < 16; x += 4) c.fillRect(x, 5, 1, 6); });
paint('shaft_end', (c) => { speckle(c, '#74777a', [['#65686c', 16]], 231, 8); c.fillStyle = '#8c8f8e'; c.fillRect(5, 2, 6, 12); c.fillRect(2, 5, 12, 6); c.fillStyle = '#6f7271'; c.fillRect(6, 6, 4, 4); c.fillStyle = '#5f6261'; c.fillRect(7, 7, 2, 2); });
paint('cog', (c) => _gear(c, '#9a9d9c', '#5f6261', 8, 5));
paint('cog_large', (c) => _gear(c, '#9a9d9c', '#565958', 12, 6.5));
paint('gearbox', (c) => { speckle(c, '#8f9291', [['#7f8281', 20]], 212, 9); _frame(c, '#5f6261'); _disc(c, 8, 8, 4, '#74787a'); _disc(c, 8, 8, 1.6, '#565958'); });
paint('water_wheel', (c) => { speckle(c, '#9a6a3a', [['#86592a', 26], ['#a8773c', 18]], 205, 10); c.strokeStyle = '#5c3d1c'; c.lineWidth = 2; c.beginPath(); c.arc(8, 8, 7, 0, 7); c.stroke(); c.fillStyle = '#5c3d1c'; c.fillRect(7, 0, 2, 16); c.fillRect(0, 7, 16, 2); _disc(c, 8, 8, 2, '#8c8f8e'); });
paint('hand_crank', (c) => { speckle(c, '#8f9291', [['#7f8281', 18]], 232, 8); c.fillStyle = '#8c8f8e'; c.fillRect(7, 6, 2, 8); c.fillStyle = '#cba74e'; c.fillRect(3, 6, 9, 3); c.fillStyle = '#9a6a3a'; c.fillRect(2, 5, 3, 5); });
paint('millstone_top', (c) => { speckle(c, '#8f9291', [['#7f8281', 22]], 206, 9); _disc(c, 8, 8, 5, '#5f6261'); _disc(c, 8, 8, 2, '#787c7e'); });
paint('millstone_side', (c) => { speckle(c, '#7c7f7e', [['#6e7170', 22]], 207, 9); c.fillStyle = '#5f6261'; c.fillRect(0, 4, 16, 1); c.fillRect(0, 11, 16, 1); c.fillStyle = '#9a6a3a'; c.fillRect(0, 12, 16, 4); });
paint('press_top', (c) => { speckle(c, '#8f9291', [['#7f8281', 20]], 209, 9); c.strokeStyle = '#6f7271'; c.strokeRect(2.5, 2.5, 11, 11); });
paint('press_side', (c) => { speckle(c, '#8f9291', [['#7f8281', 20]], 208, 9); _frame(c, '#9a6a3a'); c.fillStyle = '#5f6261'; c.fillRect(3, 3, 10, 6); c.fillStyle = '#cba74e'; c.fillRect(4, 10, 8, 4); });
paint('fan_side', (c) => { speckle(c, '#8f9291', [['#7f8281', 20]], 210, 9); _frame(c, '#9a6a3a'); _disc(c, 8, 8, 5, '#3a3a3a'); c.fillStyle = '#5f6261'; for (let i = 0; i < 4; i++) { const a = i / 4 * Math.PI * 2; c.save(); c.translate(8, 8); c.rotate(a); c.fillRect(-1, -5, 2, 5); c.restore(); } });
paint('fan_front', (c) => { speckle(c, '#6f7271', [['#5f6261', 24]], 211, 8); _disc(c, 8, 8, 6, '#3a3a3a'); _disc(c, 8, 8, 2, '#555'); });
paint('creative_motor', (c) => { speckle(c, '#3a3f4b', [['#2e323c', 20], ['#454a58', 14]], 240, 9); _frame(c, '#cba74e'); c.fillStyle = '#16d6c0'; c.fillRect(4, 4, 8, 8); c.fillStyle = '#7ef0e2'; c.fillRect(6, 6, 4, 4); c.fillStyle = '#ff5bd0'; c.fillRect(2, 2, 2, 2); c.fillRect(12, 12, 2, 2); });
paint('creative_motor_top', (c) => { speckle(c, '#3a3f4b', [['#2e323c', 20]], 241, 9); _frame(c, '#cba74e'); _disc(c, 8, 8, 3.5, '#16d6c0'); _disc(c, 8, 8, 1.6, '#7ef0e2'); });
paint('ladder', (c) => { c.clearRect(0, 0, 16, 16); c.fillStyle = '#7a5a32'; c.fillRect(2, 0, 2, 16); c.fillRect(12, 0, 2, 16); c.fillStyle = '#8a6a3f'; for (let y = 2; y < 16; y += 4) c.fillRect(2, y, 12, 2); });
paint('door', (c) => { speckle(c, '#9a6a3a', [['#86592a', 24], ['#a8773c', 16]], 250, 8); c.strokeStyle = '#5c3d1c'; c.lineWidth = 1; c.strokeRect(1.5, 1.5, 13, 6); c.strokeRect(1.5, 8.5, 13, 6); c.fillStyle = '#d8b24a'; c.fillRect(11, 7, 2, 2); });
paint('trapdoor', (c) => { speckle(c, '#9a6a3a', [['#86592a', 24]], 251, 8); c.fillStyle = '#5c3d1c'; for (let x = 1; x < 16; x += 5) c.fillRect(x, 0, 1, 16); c.fillStyle = '#4a4a4a'; c.fillRect(1, 1, 3, 2); c.fillRect(12, 1, 3, 2); });

// Block -> face tiles. Single name, or [top, side, bottom].
const FACES = {
  [BLOCK.GRASS]: ['grass_top', 'grass_side', 'dirt'],
  [BLOCK.DIRT]: 'dirt',
  [BLOCK.STONE]: 'stone',
  [BLOCK.COBBLE]: 'cobble',
  [BLOCK.MOSSY_COBBLE]: 'mossy',
  [BLOCK.STONE_BRICK]: 'stonebrick',
  [BLOCK.SAND]: 'sand',
  [BLOCK.GRAVEL]: 'gravel',
  [BLOCK.WOOD]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.WOOD_X]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.WOOD_Z]: ['wood_top', 'wood_side', 'wood_top'],
  [BLOCK.LEAVES]: 'leaves',
  [BLOCK.PLANK]: 'plank',
  [BLOCK.WATER]: 'water',
  [BLOCK.LAVA]: 'lava',
  [BLOCK.BEDROCK]: 'bedrock',
  [BLOCK.GLASS]: 'glass',
  [BLOCK.BRICK]: 'brick',
  [BLOCK.SNOW]: 'snow',
  [BLOCK.COAL_ORE]: 'coal_ore',
  [BLOCK.IRON_ORE]: 'iron_ore',
  [BLOCK.GOLD_ORE]: 'gold_ore',
  [BLOCK.DIAMOND_ORE]: 'diamond_ore',
  [BLOCK.OBSIDIAN]: 'obsidian',
  [BLOCK.NETHERRACK]: 'netherrack',
  [BLOCK.GLOWSTONE]: 'glowstone',
  [BLOCK.PORTAL]: 'portal',
  [BLOCK.CRAFTING_TABLE]: ['craft_top', 'craft_side', 'plank'],
  [BLOCK.FURNACE]: ['furnace_top', 'furnace_side', 'furnace_top'],
  [BLOCK.TORCH]: 'torch',
  [BLOCK.FARMLAND]: ['farmland', 'dirt', 'dirt'],
  [BLOCK.WHEAT0]: 'wheat0',
  [BLOCK.WHEAT1]: 'wheat1',
  [BLOCK.WHEAT2]: 'wheat2',
  [BLOCK.CHEST]: ['chest_top', 'chest_side', 'chest_top'],
  [BLOCK.SAPLING]: 'sapling',
  [BLOCK.TALL_GRASS]: 'tallgrass',
  [BLOCK.FARMLAND_WET]: ['farmland_wet', 'dirt', 'dirt'],
  [BLOCK.BED]: ['bed_top', 'bed_side', 'dirt'],
  [BLOCK.WOOL]: 'wool',
  [BLOCK.AETHER_GRASS]: ['aether_grass', 'aether_grass', 'dirt'],
  [BLOCK.AETHER_PORTAL]: 'aether_portal',
  [BLOCK.SANDSTONE]: 'sandstone',
  [BLOCK.REDSTONE_DUST]: 'rs_dust',
  [BLOCK.REDSTONE_BLOCK]: 'rs_block',
  [BLOCK.REDSTONE_TORCH]: 'rs_torch',
  [BLOCK.REDSTONE_TORCH_OFF]: 'rs_torch_off',
  [BLOCK.LEVER]: 'lever', [BLOCK.LEVER_ON]: 'lever_on',
  [BLOCK.BUTTON]: 'button', [BLOCK.BUTTON_ON]: 'button_on',
  [BLOCK.REDSTONE_LAMP]: 'lamp', [BLOCK.REDSTONE_LAMP_ON]: 'lamp_on',
  [BLOCK.REPEATER]: 'repeater', [BLOCK.REPEATER_ON]: 'repeater_on',
  [BLOCK.PISTON]: ['piston_face', 'piston_side', 'piston_side'],
  [BLOCK.PISTON_STICKY]: ['piston_face_sticky', 'piston_side', 'piston_side'],
  [BLOCK.PISTON_HEAD]: 'piston_head',
  [BLOCK.COMPARATOR]: 'comparator', [BLOCK.COMPARATOR_ON]: 'comparator_on',
  [BLOCK.END_STONE]: 'end_stone',
  [BLOCK.NETHER_BRICK]: 'nether_brick',
  [BLOCK.END_PORTAL_FRAME]: ['epf_top', 'epf_side', 'epf_side'],
  [BLOCK.END_PORTAL_FRAME_EYE]: ['epf_eye', 'epf_side', 'epf_side'],
  [BLOCK.END_PORTAL]: 'end_portal',
  [BLOCK.DRAGON_EGG]: 'dragon_egg',
  // kinetics
  [BLOCK.ANDESITE_CASING]: ['andesite_casing_top', 'andesite_casing', 'andesite_casing_top'],
  [BLOCK.BRASS_CASING]: ['brass_casing_top', 'brass_casing', 'brass_casing_top'],
  [BLOCK.SHAFT]: ['shaft_end', 'shaft_side', 'shaft_end'],
  [BLOCK.COGWHEEL]: 'cog',
  [BLOCK.LARGE_COGWHEEL]: 'cog_large',
  [BLOCK.GEARBOX]: 'gearbox',
  [BLOCK.WATER_WHEEL]: 'water_wheel',
  [BLOCK.HAND_CRANK]: 'hand_crank',
  [BLOCK.MILLSTONE]: ['millstone_top', 'millstone_side', 'millstone_side'],
  [BLOCK.MECHANICAL_PRESS]: ['press_top', 'press_side', 'press_top'],
  [BLOCK.ENCASED_FAN]: ['fan_front', 'fan_side', 'fan_side'],
  [BLOCK.CREATIVE_MOTOR]: ['creative_motor_top', 'creative_motor', 'creative_motor_top'],
  // building blocks reuse their material's tiles
  [BLOCK.SLAB_STONE]: 'stone', [BLOCK.STAIRS_STONE]: 'stone',
  [BLOCK.SLAB_COBBLE]: 'cobble', [BLOCK.STAIRS_COBBLE]: 'cobble',
  [BLOCK.SLAB_PLANK]: 'plank', [BLOCK.STAIRS_PLANK]: 'plank', [BLOCK.FENCE]: 'plank',
  [BLOCK.SLAB_BRICK]: 'brick', [BLOCK.STAIRS_BRICK]: 'brick',
  [BLOCK.GLASS_PANE]: 'glass',
  [BLOCK.LADDER]: 'ladder', [BLOCK.DOOR]: 'door', [BLOCK.TRAPDOOR]: 'trapdoor',
};
for (const [id, tile] of WOOL_COLORS) FACES[id] = tile;

// Oriented logs: which axis shows the "ring" end-grain.
const LOGS = {
  [BLOCK.WOOD]:   { axis: 'y', ring: 'wood_top', bark: 'wood_side' },
  [BLOCK.WOOD_X]: { axis: 'x', ring: 'wood_top', bark: 'wood_side' },
  [BLOCK.WOOD_Z]: { axis: 'z', ring: 'wood_top', bark: 'wood_side' },
};

// Block metadata used by gameplay / rendering.
const BLOCK_INFO = {
  [BLOCK.GRASS]:  { name: 'Grass',       solid: true,  color: '#5fa83d' },
  [BLOCK.DIRT]:   { name: 'Dirt',        solid: true,  color: '#7a5a3a' },
  [BLOCK.STONE]:  { name: 'Stone',       solid: true,  color: '#888888' },
  [BLOCK.COBBLE]: { name: 'Cobblestone', solid: true,  color: '#7c7c7c' },
  [BLOCK.MOSSY_COBBLE]: { name: 'Mossy Cobble', solid: true, color: '#6e7a5c' },
  [BLOCK.STONE_BRICK]: { name: 'Stone Bricks', solid: true, color: '#8a8a8a' },
  [BLOCK.SAND]:   { name: 'Sand',        solid: true,  color: '#dcd29a' },
  [BLOCK.GRAVEL]: { name: 'Gravel',      solid: true,  color: '#9a938c' },
  [BLOCK.WOOD]:   { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.WOOD_X]: { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.WOOD_Z]: { name: 'Wood Log',    solid: true,  color: '#6b4f2f' },
  [BLOCK.LEAVES]: { name: 'Leaves',      solid: true,  color: '#3f8f33', transparent: true },
  [BLOCK.PLANK]:  { name: 'Planks',      solid: true,  color: '#b08a52' },
  [BLOCK.WATER]:  { name: 'Water',       solid: false, color: '#2b6fd6', transparent: true, liquid: true },
  [BLOCK.LAVA]:   { name: 'Lava',        solid: false, color: '#e2541a', transparent: true, liquid: true, hot: true, emit: 12 },
  [BLOCK.BEDROCK]:{ name: 'Bedrock',     solid: true,  color: '#3a3a3a', unbreakable: true },
  [BLOCK.GLASS]:  { name: 'Glass',       solid: true,  color: '#bfe0ec', transparent: true },
  [BLOCK.BRICK]:  { name: 'Bricks',      solid: true,  color: '#a44a3a' },
  [BLOCK.SNOW]:   { name: 'Snow',        solid: true,  color: '#f2f7fb' },
  [BLOCK.COAL_ORE]:    { name: 'Coal Ore',    solid: true, color: '#888888' },
  [BLOCK.IRON_ORE]:    { name: 'Iron Ore',    solid: true, color: '#888888' },
  [BLOCK.GOLD_ORE]:    { name: 'Gold Ore',    solid: true, color: '#888888' },
  [BLOCK.DIAMOND_ORE]: { name: 'Diamond Ore', solid: true, color: '#888888' },
  [BLOCK.OBSIDIAN]:    { name: 'Obsidian',    solid: true, color: '#15101f' },
  [BLOCK.NETHERRACK]:  { name: 'Netherrack',  solid: true, color: '#5e2a2a' },
  [BLOCK.GLOWSTONE]:   { name: 'Glowstone',   solid: true, color: '#d8a93a', emit: 15 },
  [BLOCK.PORTAL]:      { name: 'Nether Portal', solid: false, color: '#7a28c8', transparent: true, portal: true, emit: 6 },
  [BLOCK.CRAFTING_TABLE]: { name: 'Crafting Table', solid: true, color: '#9c7a47' },
  [BLOCK.FURNACE]: { name: 'Furnace', solid: true, color: '#7c7c7c' },
  [BLOCK.TORCH]:   { name: 'Torch', solid: false, color: '#ffcf6b', transparent: true, emit: 14 },
  [BLOCK.FARMLAND]: { name: 'Farmland', solid: true, color: '#5a3d24' },
  [BLOCK.WHEAT0]:  { name: 'Wheat', solid: false, color: '#5fa83d', transparent: true, crop: true },
  [BLOCK.WHEAT1]:  { name: 'Wheat', solid: false, color: '#5a9a35', transparent: true, crop: true },
  [BLOCK.WHEAT2]:  { name: 'Wheat', solid: false, color: '#c8a93a', transparent: true, crop: true },
  [BLOCK.CHEST]:   { name: 'Chest', solid: true, color: '#9a6b34' },
  [BLOCK.SAPLING]: { name: 'Sapling', solid: false, color: '#3f8f33', transparent: true, crop: true },
  [BLOCK.TALL_GRASS]: { name: 'Tall Grass', solid: false, color: '#5fa83d', transparent: true, crop: true },
  [BLOCK.FARMLAND_WET]: { name: 'Wet Farmland', solid: true, color: '#3a2a16' },
  [BLOCK.BED]: { name: 'Bed', solid: true, color: '#c0392b' },
  [BLOCK.WOOL]: { name: 'Wool', solid: true, color: '#ececec' },
  [BLOCK.AETHER_GRASS]: { name: 'Aether Grass', solid: true, color: '#9fe0c0' },
  [BLOCK.AETHER_PORTAL]: { name: 'Aether Portal', solid: false, color: '#96dcff', transparent: true, portal: true, emit: 8 },
  [BLOCK.SANDSTONE]: { name: 'Sandstone', solid: true, color: '#dcd29a' },
  // redstone (rs:true makes a non-solid component targetable + alpha-rendered)
  [BLOCK.REDSTONE_DUST]: { name: 'Redstone Dust', solid: false, transparent: true, rs: true, color: '#b02a18' },
  [BLOCK.REDSTONE_BLOCK]: { name: 'Redstone Block', solid: true, color: '#b5251a' },
  [BLOCK.REDSTONE_TORCH]: { name: 'Redstone Torch', solid: false, transparent: true, rs: true, color: '#ff3b22', emit: 7 },
  [BLOCK.REDSTONE_TORCH_OFF]: { name: 'Redstone Torch', solid: false, transparent: true, rs: true, color: '#7a261a' },
  [BLOCK.LEVER]: { name: 'Lever', solid: false, transparent: true, rs: true, color: '#9c7a47' },
  [BLOCK.LEVER_ON]: { name: 'Lever', solid: false, transparent: true, rs: true, color: '#9c7a47' },
  [BLOCK.BUTTON]: { name: 'Button', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.BUTTON_ON]: { name: 'Button', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.REDSTONE_LAMP]: { name: 'Redstone Lamp', solid: true, color: '#6a5a3a' },
  [BLOCK.REDSTONE_LAMP_ON]: { name: 'Redstone Lamp', solid: true, color: '#f0c860', emit: 15 },
  [BLOCK.REPEATER]: { name: 'Repeater', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.REPEATER_ON]: { name: 'Repeater', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.PISTON]: { name: 'Piston', solid: true, color: '#9a8a6a' },
  [BLOCK.PISTON_STICKY]: { name: 'Sticky Piston', solid: true, color: '#9a8a6a' },
  [BLOCK.PISTON_HEAD]: { name: 'Piston Head', solid: true, color: '#caa86a' },
  [BLOCK.COMPARATOR]: { name: 'Comparator', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.COMPARATOR_ON]: { name: 'Comparator', solid: false, transparent: true, rs: true, color: '#9a9a9a' },
  [BLOCK.END_STONE]: { name: 'End Stone', solid: true, color: '#dcdca4' },
  [BLOCK.NETHER_BRICK]: { name: 'Nether Bricks', solid: true, color: '#39202a' },
  [BLOCK.END_PORTAL_FRAME]: { name: 'End Portal Frame', solid: true, color: '#5b6b54', emit: 1 },
  [BLOCK.END_PORTAL_FRAME_EYE]: { name: 'End Portal Frame', solid: true, color: '#5b6b54', emit: 4 },
  [BLOCK.END_PORTAL]: { name: 'End Portal', solid: false, transparent: true, portal: true, color: '#0a0a16', emit: 11 },
  [BLOCK.DRAGON_EGG]: { name: 'Dragon Egg', solid: true, color: '#190f24', emit: 3 },
  // kinetics (cogs/shafts are transparent so the spinning overlay reads through)
  [BLOCK.ANDESITE_CASING]: { name: 'Andesite Casing', solid: true, color: '#8f9291' },
  [BLOCK.BRASS_CASING]: { name: 'Brass Casing', solid: true, color: '#cba74e' },
  // shaft/cog/wheel/crank are drawn as 3D models, not cubes (see MODEL_BLOCKS);
  // transparent here only means "don't cull my neighbours' faces".
  [BLOCK.SHAFT]: { name: 'Shaft', solid: true, transparent: true, model: true, color: '#8c8f8e' },
  [BLOCK.COGWHEEL]: { name: 'Cogwheel', solid: true, transparent: true, model: true, color: '#9a9d9c' },
  [BLOCK.LARGE_COGWHEEL]: { name: 'Large Cogwheel', solid: true, transparent: true, model: true, color: '#9a9d9c' },
  [BLOCK.GEARBOX]: { name: 'Gearbox', solid: true, color: '#8f9291' },
  [BLOCK.WATER_WHEEL]: { name: 'Water Wheel', solid: true, transparent: true, model: true, color: '#9a6a3a' },
  [BLOCK.HAND_CRANK]: { name: 'Hand Crank', solid: true, transparent: true, model: true, color: '#cba74e' },
  [BLOCK.MILLSTONE]: { name: 'Millstone', solid: true, color: '#7c7f7e' },
  [BLOCK.MECHANICAL_PRESS]: { name: 'Mechanical Press', solid: true, color: '#8f9291' },
  [BLOCK.ENCASED_FAN]: { name: 'Encased Fan', solid: true, color: '#8f9291' },
  [BLOCK.CREATIVE_MOTOR]: { name: 'Creative Motor', solid: true, color: '#16d6c0', emit: 4 },
  // building blocks (solid for collision, transparent so they don't cull neighbours)
  [BLOCK.SLAB_STONE]: { name: 'Stone Slab', solid: true, transparent: true, color: '#888888' },
  [BLOCK.SLAB_COBBLE]: { name: 'Cobblestone Slab', solid: true, transparent: true, color: '#7c7c7c' },
  [BLOCK.SLAB_PLANK]: { name: 'Plank Slab', solid: true, transparent: true, color: '#b08a52' },
  [BLOCK.SLAB_BRICK]: { name: 'Brick Slab', solid: true, transparent: true, color: '#a44a3a' },
  [BLOCK.STAIRS_STONE]: { name: 'Stone Stairs', solid: true, transparent: true, color: '#888888' },
  [BLOCK.STAIRS_COBBLE]: { name: 'Cobblestone Stairs', solid: true, transparent: true, color: '#7c7c7c' },
  [BLOCK.STAIRS_PLANK]: { name: 'Plank Stairs', solid: true, transparent: true, color: '#b08a52' },
  [BLOCK.STAIRS_BRICK]: { name: 'Brick Stairs', solid: true, transparent: true, color: '#a44a3a' },
  [BLOCK.FENCE]: { name: 'Fence', solid: true, transparent: true, color: '#b08a52' },
  [BLOCK.GLASS_PANE]: { name: 'Glass Pane', solid: true, transparent: true, alpha: true, color: '#bfe0ec' },
  [BLOCK.LADDER]: { name: 'Ladder', solid: false, transparent: true, climb: true, color: '#7a5a32' },
  [BLOCK.DOOR]: { name: 'Door', solid: true, transparent: true, color: '#9a6a3a' },
  [BLOCK.TRAPDOOR]: { name: 'Trapdoor', solid: true, transparent: true, color: '#9a6a3a' },
};
// redstone helper sets
const RS_COMPONENT = new Set([
  BLOCK.REDSTONE_DUST, BLOCK.REDSTONE_BLOCK, BLOCK.REDSTONE_TORCH, BLOCK.REDSTONE_TORCH_OFF,
  BLOCK.LEVER, BLOCK.LEVER_ON, BLOCK.BUTTON, BLOCK.BUTTON_ON,
  BLOCK.REDSTONE_LAMP, BLOCK.REDSTONE_LAMP_ON, BLOCK.REPEATER, BLOCK.REPEATER_ON,
  BLOCK.PISTON, BLOCK.PISTON_STICKY,
]);
for (const [id, , color, name] of WOOL_COLORS) BLOCK_INFO[id] = { name, solid: true, color };

// light emitted by a block (0-15)
function blockEmit(id) { const i = BLOCK_INFO[id]; return (i && i.emit) || 0; }
// does light pass through this block?
function lightPasses(id) { return id === BLOCK.AIR || (BLOCK_INFO[id] && BLOCK_INFO[id].transparent); }

// ---- mining: hardness (seconds by hand), preferred tool, drop gating ----
const HARDNESS = {
  default: 0.6,
  [BLOCK.LEAVES]: 0.2, [BLOCK.GLASS]: 0.3, [BLOCK.SNOW]: 0.4, [BLOCK.TORCH]: 0.05,
  [BLOCK.DIRT]: 0.6, [BLOCK.GRASS]: 0.6, [BLOCK.SAND]: 0.5, [BLOCK.GRAVEL]: 0.6,
  [BLOCK.FARMLAND]: 0.6, [BLOCK.FARMLAND_WET]: 0.6, [BLOCK.WHEAT0]: 0.05, [BLOCK.WHEAT1]: 0.05, [BLOCK.WHEAT2]: 0.05,
  [BLOCK.SAPLING]: 0.05, [BLOCK.TALL_GRASS]: 0.02, [BLOCK.BED]: 0.4, [BLOCK.WOOL]: 0.4,
  [BLOCK.AETHER_GRASS]: 0.6,
  [BLOCK.WOOD]: 1.6, [BLOCK.WOOD_X]: 1.6, [BLOCK.WOOD_Z]: 1.6, [BLOCK.PLANK]: 1.6, [BLOCK.CRAFTING_TABLE]: 1.6, [BLOCK.CHEST]: 1.6,
  [BLOCK.STONE]: 2.2, [BLOCK.COBBLE]: 2.2, [BLOCK.MOSSY_COBBLE]: 2.2, [BLOCK.STONE_BRICK]: 2.2, [BLOCK.BRICK]: 2.2,
  [BLOCK.FURNACE]: 3.5,
  [BLOCK.COAL_ORE]: 3, [BLOCK.IRON_ORE]: 3, [BLOCK.GOLD_ORE]: 3, [BLOCK.DIAMOND_ORE]: 3,
  [BLOCK.NETHERRACK]: 0.8, [BLOCK.GLOWSTONE]: 0.5, [BLOCK.OBSIDIAN]: 9,
  [BLOCK.END_STONE]: 3, [BLOCK.NETHER_BRICK]: 2.2, [BLOCK.DRAGON_EGG]: 3,
  [BLOCK.END_PORTAL_FRAME]: 9, [BLOCK.END_PORTAL_FRAME_EYE]: 9,
  [BLOCK.ANDESITE_CASING]: 1.6, [BLOCK.BRASS_CASING]: 1.6, [BLOCK.GEARBOX]: 1.6,
  [BLOCK.SHAFT]: 0.8, [BLOCK.COGWHEEL]: 0.8, [BLOCK.LARGE_COGWHEEL]: 0.8,
  [BLOCK.WATER_WHEEL]: 1.6, [BLOCK.HAND_CRANK]: 0.8,
  [BLOCK.MILLSTONE]: 3, [BLOCK.MECHANICAL_PRESS]: 3, [BLOCK.ENCASED_FAN]: 2.2, [BLOCK.CREATIVE_MOTOR]: 2.2,
  [BLOCK.SLAB_STONE]: 2.2, [BLOCK.SLAB_COBBLE]: 2.2, [BLOCK.SLAB_BRICK]: 2.2, [BLOCK.SLAB_PLANK]: 1.6,
  [BLOCK.STAIRS_STONE]: 2.2, [BLOCK.STAIRS_COBBLE]: 2.2, [BLOCK.STAIRS_BRICK]: 2.2, [BLOCK.STAIRS_PLANK]: 1.6,
  [BLOCK.FENCE]: 1.6, [BLOCK.GLASS_PANE]: 0.3,
  [BLOCK.LADDER]: 0.4, [BLOCK.DOOR]: 1.6, [BLOCK.TRAPDOOR]: 1.6,
};
function blockHardness(id) {
  const i = BLOCK_INFO[id];
  if (!i) return 0;
  if (i.unbreakable) return Infinity;
  return HARDNESS[id] != null ? HARDNESS[id] : HARDNESS.default;
}
// Which tool type mines a block fastest.
const BLOCK_TOOL = {
  [BLOCK.STONE]: 'pickaxe', [BLOCK.COBBLE]: 'pickaxe', [BLOCK.MOSSY_COBBLE]: 'pickaxe',
  [BLOCK.STONE_BRICK]: 'pickaxe', [BLOCK.BRICK]: 'pickaxe',
  [BLOCK.COAL_ORE]: 'pickaxe', [BLOCK.IRON_ORE]: 'pickaxe', [BLOCK.GOLD_ORE]: 'pickaxe',
  [BLOCK.DIAMOND_ORE]: 'pickaxe', [BLOCK.OBSIDIAN]: 'pickaxe',
  [BLOCK.NETHERRACK]: 'pickaxe', [BLOCK.GLOWSTONE]: 'pickaxe',
  [BLOCK.FURNACE]: 'pickaxe',
  [BLOCK.END_STONE]: 'pickaxe', [BLOCK.NETHER_BRICK]: 'pickaxe',
  [BLOCK.END_PORTAL_FRAME]: 'pickaxe', [BLOCK.END_PORTAL_FRAME_EYE]: 'pickaxe',
  [BLOCK.ANDESITE_CASING]: 'pickaxe', [BLOCK.BRASS_CASING]: 'pickaxe', [BLOCK.GEARBOX]: 'pickaxe',
  [BLOCK.MILLSTONE]: 'pickaxe', [BLOCK.MECHANICAL_PRESS]: 'pickaxe', [BLOCK.ENCASED_FAN]: 'pickaxe', [BLOCK.CREATIVE_MOTOR]: 'pickaxe',
  [BLOCK.SLAB_STONE]: 'pickaxe', [BLOCK.SLAB_COBBLE]: 'pickaxe', [BLOCK.SLAB_BRICK]: 'pickaxe',
  [BLOCK.STAIRS_STONE]: 'pickaxe', [BLOCK.STAIRS_COBBLE]: 'pickaxe', [BLOCK.STAIRS_BRICK]: 'pickaxe',
  [BLOCK.SLAB_PLANK]: 'axe', [BLOCK.STAIRS_PLANK]: 'axe', [BLOCK.FENCE]: 'axe',
  [BLOCK.DOOR]: 'axe', [BLOCK.TRAPDOOR]: 'axe', [BLOCK.LADDER]: 'axe',
  [BLOCK.WOOD]: 'axe', [BLOCK.WOOD_X]: 'axe', [BLOCK.WOOD_Z]: 'axe',
  [BLOCK.PLANK]: 'axe', [BLOCK.CRAFTING_TABLE]: 'axe', [BLOCK.CHEST]: 'axe',
  [BLOCK.DIRT]: 'shovel', [BLOCK.GRASS]: 'shovel', [BLOCK.SAND]: 'shovel',
  [BLOCK.GRAVEL]: 'shovel', [BLOCK.SNOW]: 'shovel',
};
// Blocks that only drop an item when mined with the correct (pickaxe) tool.
const NEEDS_TOOL = new Set([
  BLOCK.STONE, BLOCK.COBBLE, BLOCK.MOSSY_COBBLE, BLOCK.STONE_BRICK, BLOCK.BRICK,
  BLOCK.COAL_ORE, BLOCK.IRON_ORE, BLOCK.GOLD_ORE, BLOCK.DIAMOND_ORE, BLOCK.OBSIDIAN,
  BLOCK.FURNACE, BLOCK.END_STONE, BLOCK.NETHER_BRICK,
  BLOCK.END_PORTAL_FRAME, BLOCK.END_PORTAL_FRAME_EYE,
]);

// Blocks shown as standalone 3D models (rods/gears/wheels) instead of full
// cubes — the chunk mesher skips them and create.js renders the model.
const MODEL_BLOCKS = new Set([BLOCK.SHAFT, BLOCK.COGWHEEL, BLOCK.LARGE_COGWHEEL, BLOCK.WATER_WHEEL, BLOCK.HAND_CRANK]);

// ---- partial-shape building blocks (slabs / stairs / fences / panes) ----
const SLABS = new Set([BLOCK.SLAB_STONE, BLOCK.SLAB_COBBLE, BLOCK.SLAB_PLANK, BLOCK.SLAB_BRICK]);
const STAIRS = new Set([BLOCK.STAIRS_STONE, BLOCK.STAIRS_COBBLE, BLOCK.STAIRS_PLANK, BLOCK.STAIRS_BRICK]);
const SHAPED = new Set([...SLABS, ...STAIRS, BLOCK.FENCE, BLOCK.GLASS_PANE, BLOCK.LADDER, BLOCK.DOOR, BLOCK.TRAPDOOR]);
// a thin slab pressed against wall side `f` (0:-z 1:+x 2:+z 3:-x)
function _wallPlate(f, t) {
  if (f === 0) return [0, 0, 0, 1, 1, t];
  if (f === 2) return [0, 0, 1 - t, 1, 1, 1];
  if (f === 1) return [1 - t, 0, 0, 1, 1, 1];
  return [0, 0, 0, t, 1, 1];
}
function isOccluder(id) { const i = BLOCK_INFO[id]; return id !== BLOCK.AIR && i && i.solid && !i.transparent; }
function _fenceJoins(id) { return id !== BLOCK.AIR && (isOccluder(id) || id === BLOCK.FENCE); }
function _paneJoins(id) { return id !== BLOCK.AIR && (isOccluder(id) || id === BLOCK.GLASS || id === BLOCK.GLASS_PANE); }

// The set of [x0,y0,z0,x1,y1,z1] boxes (0..1 local) a shaped block occupies.
// meta = { f:facing 0-3, h:'top'|'bottom' }; nbr(dx,dy,dz) -> neighbour block id.
function shapeBoxes(id, meta, nbr) {
  if (SLABS.has(id)) return [meta && meta.h === 'top' ? [0, 0.5, 0, 1, 1, 1] : [0, 0, 0, 1, 0.5, 1]];
  if (STAIRS.has(id)) {
    const top = meta && meta.h === 'top';
    const by0 = top ? 0.5 : 0, by1 = top ? 1 : 0.5, sy0 = top ? 0 : 0.5, sy1 = top ? 0.5 : 1;
    const f = (meta && meta.f) || 0, boxes = [[0, by0, 0, 1, by1, 1]];
    if (f === 0) boxes.push([0, sy0, 0, 1, sy1, 0.5]);
    else if (f === 2) boxes.push([0, sy0, 0.5, 1, sy1, 1]);
    else if (f === 1) boxes.push([0.5, sy0, 0, 1, sy1, 1]);
    else boxes.push([0, sy0, 0, 0.5, sy1, 1]);
    return boxes;
  }
  if (id === BLOCK.FENCE) {
    const a = 6 / 16, b = 10 / 16, boxes = [[a, 0, a, b, 1, b]];
    if (_fenceJoins(nbr(-1, 0, 0))) { boxes.push([0, 6 / 16, a, a, 9 / 16, b], [0, 12 / 16, a, a, 15 / 16, b]); }
    if (_fenceJoins(nbr(1, 0, 0))) { boxes.push([b, 6 / 16, a, 1, 9 / 16, b], [b, 12 / 16, a, 1, 15 / 16, b]); }
    if (_fenceJoins(nbr(0, 0, -1))) { boxes.push([a, 6 / 16, 0, b, 9 / 16, a], [a, 12 / 16, 0, b, 15 / 16, a]); }
    if (_fenceJoins(nbr(0, 0, 1))) { boxes.push([a, 6 / 16, b, b, 9 / 16, 1], [a, 12 / 16, b, b, 15 / 16, 1]); }
    return boxes;
  }
  if (id === BLOCK.GLASS_PANE) {
    const a = 7 / 16, b = 9 / 16;
    const L = _paneJoins(nbr(-1, 0, 0)), R = _paneJoins(nbr(1, 0, 0)), N = _paneJoins(nbr(0, 0, -1)), S = _paneJoins(nbr(0, 0, 1));
    if (!(L || R || N || S)) return [[a, 0, 0, b, 1, 1], [0, 0, a, 1, 1, b]];   // lone pane = full cross
    const boxes = [[a, 0, a, b, 1, b]];
    if (L) boxes.push([0, 0, a, a, 1, b]); if (R) boxes.push([b, 0, a, 1, 1, b]);
    if (N) boxes.push([a, 0, 0, b, 1, a]); if (S) boxes.push([a, 0, b, b, 1, 1]);
    return boxes;
  }
  if (id === BLOCK.LADDER) return [_wallPlate((meta && meta.f) || 2, 2 / 16)];
  if (id === BLOCK.DOOR) {
    const f = (meta && meta.f) || 0;
    return [_wallPlate((meta && meta.open) ? (f + 1) % 4 : f, 3 / 16)];   // swings 90° when open
  }
  if (id === BLOCK.TRAPDOOR) {
    if (meta && meta.open) return [_wallPlate((meta && meta.f) || 0, 3 / 16)];
    return [meta && meta.h === 'top' ? [0, 13 / 16, 0, 1, 1, 1] : [0, 0, 0, 1, 3 / 16, 1]];
  }
  return [[0, 0, 0, 1, 1, 1]];
}

// Blocks offered in the build palette / inventory.
const PALETTE = [
  BLOCK.GRASS, BLOCK.DIRT, BLOCK.STONE, BLOCK.COBBLE, BLOCK.MOSSY_COBBLE, BLOCK.STONE_BRICK,
  BLOCK.SAND, BLOCK.GRAVEL, BLOCK.WOOD, BLOCK.PLANK, BLOCK.CRAFTING_TABLE, BLOCK.FURNACE, BLOCK.CHEST, BLOCK.LEAVES,
  BLOCK.GLASS, BLOCK.BRICK, BLOCK.SNOW,
  BLOCK.COAL_ORE, BLOCK.IRON_ORE, BLOCK.GOLD_ORE, BLOCK.DIAMOND_ORE,
  BLOCK.OBSIDIAN, BLOCK.NETHERRACK, BLOCK.GLOWSTONE, BLOCK.TORCH, BLOCK.BED, BLOCK.WOOL, BLOCK.SANDSTONE,
  BLOCK.END_STONE, BLOCK.NETHER_BRICK, BLOCK.END_PORTAL_FRAME, BLOCK.DRAGON_EGG,
  BLOCK.REDSTONE_DUST, BLOCK.REDSTONE_BLOCK, BLOCK.REDSTONE_TORCH, BLOCK.LEVER, BLOCK.BUTTON,
  BLOCK.REDSTONE_LAMP, BLOCK.REPEATER, BLOCK.COMPARATOR, BLOCK.PISTON, BLOCK.PISTON_STICKY,
  BLOCK.ANDESITE_CASING, BLOCK.BRASS_CASING, BLOCK.SHAFT, BLOCK.COGWHEEL, BLOCK.LARGE_COGWHEEL,
  BLOCK.GEARBOX, BLOCK.WATER_WHEEL, BLOCK.HAND_CRANK, BLOCK.CREATIVE_MOTOR,
  BLOCK.MILLSTONE, BLOCK.MECHANICAL_PRESS, BLOCK.ENCASED_FAN,
  BLOCK.SLAB_STONE, BLOCK.SLAB_COBBLE, BLOCK.SLAB_PLANK, BLOCK.SLAB_BRICK,
  BLOCK.STAIRS_STONE, BLOCK.STAIRS_COBBLE, BLOCK.STAIRS_PLANK, BLOCK.STAIRS_BRICK,
  BLOCK.FENCE, BLOCK.GLASS_PANE, BLOCK.LADDER, BLOCK.DOOR, BLOCK.TRAPDOOR,
];

// ---- atlas + icons ----
let _atlas = null, _tileUV = null, _icons = {};

function _iconTile(blockId) {
  if (blockId === BLOCK.GRASS) return 'grass_top';
  const log = LOGS[blockId];
  if (log) return log.bark;
  const f = FACES[blockId];
  return Array.isArray(f) ? f[1] : f;
}

function buildAtlas() {
  if (_atlas) return { texture: _atlas, tileUV: _tileUV };
  const TS = 16;
  const cols = Math.ceil(Math.sqrt(tileOrder.length));
  const rows = Math.ceil(tileOrder.length / cols);
  const canvas = document.createElement('canvas');
  canvas.width = cols * TS; canvas.height = rows * TS;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;

  _tileUV = {};
  tileOrder.forEach((name, i) => {
    const cx = (i % cols) * TS, cy = ((i / cols) | 0) * TS;
    const tc = document.createElement('canvas'); tc.width = TS; tc.height = TS;
    const tctx = tc.getContext('2d'); tctx.imageSmoothingEnabled = false;
    TILE[name](tctx);
    ctx.drawImage(tc, cx, cy);
    const pad = 0.05;
    _tileUV[name] = [
      (cx + pad) / canvas.width, 1 - (cy + TS - pad) / canvas.height,
      (cx + TS - pad) / canvas.width, 1 - (cy + pad) / canvas.height,
    ];
    TILE[name]._canvas = tc;   // keep for icon export
  });

  // build per-block icon data URLs for every renderable block (scaled up, crisp)
  for (const id of Object.keys(FACES).map(Number)) {
    const tile = _iconTile(id);
    const ic = document.createElement('canvas'); ic.width = 32; ic.height = 32;
    const ictx = ic.getContext('2d'); ictx.imageSmoothingEnabled = false;
    const src = TILE[tile]._canvas;
    // shaped blocks get a silhouette icon so you can tell them apart
    if (SLABS.has(id)) {
      ictx.drawImage(src, 0, 8, 16, 8, 0, 16, 32, 16);                 // bottom half
    } else if (STAIRS.has(id)) {
      ictx.drawImage(src, 0, 8, 16, 8, 0, 16, 32, 16);                 // bottom step
      ictx.drawImage(src, 0, 0, 8, 8, 0, 0, 16, 16);                   // upper-back step
    } else if (id === BLOCK.FENCE) {
      ictx.drawImage(src, 6, 0, 4, 16, 13, 1, 6, 31);                  // post
      ictx.drawImage(src, 0, 6, 16, 4, 0, 12, 32, 7);                  // rail
    } else if (id === BLOCK.GLASS_PANE) {
      ictx.drawImage(src, 7, 0, 2, 16, 13, 0, 6, 32);                  // thin pane
    } else {
      ictx.drawImage(src, 0, 0, 32, 32);
    }
    _icons[id] = ic.toDataURL ? ic.toDataURL() : '';
  }

  const tex = new THREE.CanvasTexture(canvas);
  tex.magFilter = THREE.NearestFilter; tex.minFilter = THREE.NearestFilter;
  tex.generateMipmaps = false; tex.colorSpace = THREE.SRGBColorSpace;
  _atlas = tex;
  return { texture: _atlas, tileUV: _tileUV };
}

// UV rect for a face. `face` is one of 'py','ny','px','nx','pz','nz'.
function faceUV(blockId, face) {
  const log = LOGS[blockId];
  if (log) {
    const axis = face[1];                       // 'y' from 'py', 'x' from 'nx', etc.
    return _tileUV[axis === log.axis ? log.ring : log.bark];
  }
  const f = FACES[blockId];
  if (Array.isArray(f)) return _tileUV[face === 'py' ? f[0] : face === 'ny' ? f[2] : f[1]];
  return _tileUV[f];
}

function blockIcon(blockId) { return _icons[blockId] || ''; }
